"""Generates prompts-image.js — the image-to-image transformation prompt library.

Each style has a hand-written descriptor. Wrapper phrasing and preservation
clauses rotate per category so prompts stay varied instead of templated.
Re-run this any time you add styles below:  python3 build_prompts.py
"""

import json
import os

# (style name, descriptor injected into the prompt)
CATALOG = {
    "Traditional Media": [
        ("Watercolor Painting", "a soft watercolor painting with bleeding edges, visible paper texture and translucent washes"),
        ("Oil Painting", "a rich oil painting with thick visible brushwork and deep layered colour"),
        ("Impasto Oil", "a heavy impasto oil painting where the paint stands off the canvas in thick ridges"),
        ("Acrylic Painting", "a bold acrylic painting with flat opaque colour blocks and crisp edges"),
        ("Gouache Illustration", "a gouache illustration with heavy matte pigment and deep saturated flats"),
        ("Pencil Sketch", "a graphite pencil sketch with visible hatching, construction lines and soft smudged shading"),
        ("Detailed Graphite Portrait", "a highly detailed graphite portrait drawing with smooth tonal gradients and sharp highlights"),
        ("Colored Pencil", "a coloured pencil drawing with visible directional strokes and layered pigment"),
        ("Charcoal Drawing", "a charcoal drawing with smoky gradients, deep blacks and smudged edges"),
        ("Conte Crayon", "a conte crayon drawing in earthy red and black tones on toned paper"),
        ("Ink Pen Hatching", "a fine ink pen drawing built entirely from cross-hatching and stippling"),
        ("Ink Wash", "an ink wash painting with fluid brushstrokes and varying opacity of black and grey"),
        ("Brush Pen Illustration", "a brush pen illustration with confident tapering strokes and bold black fills"),
        ("Pastel Drawing", "a soft pastel drawing with chalky powdery texture and gentle blended colour"),
        ("Oil Pastel", "an oil pastel drawing with waxy blended strokes and rich saturated colour"),
        ("Crayon Drawing", "a childlike crayon drawing with waxy scribbled fill and shaky outlines"),
        ("Marker Illustration", "an alcohol marker illustration with flat streaky fills and clean ink linework"),
        ("Airbrush Art", "a smooth airbrushed illustration with soft gradients and glossy highlights"),
        ("Scratchboard", "a scratchboard engraving with fine white lines scratched out of solid black"),
        ("Etching Print", "a copperplate etching print with fine engraved lines and aged paper tone"),
        ("Lithograph", "a vintage lithograph print with grainy tonal texture and limited ink colours"),
        ("Woodblock Print", "a traditional woodblock print with strong black outlines and flat colour zones"),
        ("Linocut Print", "a linocut print with bold blocky negative space and raw chiselled edges"),
        ("Screen Print", "a screen print with flat spot colours, slight registration offset and visible ink texture"),
        ("Risograph Print", "a risograph print with misaligned two-colour layers, visible grain and a limited palette"),
        ("Halftone Print", "a coarse halftone print built from visible dot patterns and limited ink colours"),
        ("Stained Glass", "a stained glass panel with bold black leading sealing glowing translucent colour"),
        ("Mosaic Tile", "a mosaic built from small irregular ceramic tiles with visible grout lines"),
        ("Fresco Mural", "a cracked plaster fresco with faded historical pigment and worn patches"),
        ("Tempera Panel", "an egg tempera panel painting with fine hatched brushwork and matte finish"),
        ("Encaustic Wax", "an encaustic wax painting with translucent layered surfaces and fused texture"),
        ("Paper Collage", "a torn paper collage with layered cut edges and mixed printed textures"),
        ("Stencil Spray Art", "a multi-layer stencil spray painting with hard edges and overspray texture"),
        ("Graffiti Mural", "a spray-painted graffiti mural with bold outlines, drips and vivid fills"),
        ("Chalkboard Drawing", "a white chalk drawing on a dark textured chalkboard with dusty smudges"),
        ("Sand Art", "an image formed from shifting granular sand in warm brown tones"),
        ("Embroidery", "a hand-embroidered piece built from visible coloured threads on woven fabric"),
        ("Cross-Stitch", "a cross-stitch pattern made from small X-shaped stitches on visible aida cloth"),
    ],
    "Illustration & Animation": [
        ("Hand-Painted Anime Film", "a hand-painted anime film frame with soft cel shading, detailed painted backgrounds and warm natural light"),
        ("Soft Cel Animation", "a soft cel animation frame with gentle line work, flat shading and a painted background"),
        ("Retro 80s Anime", "a 1980s anime cel with thick hand-inked lines, visible paint texture and film grain"),
        ("90s Anime", "a 1990s anime frame with rich cel colour, sharp shadow shapes and slight film softness"),
        ("Modern Digital Anime", "a modern digital anime frame with crisp clean lines, smooth gradients and bright colour"),
        ("Classic 2D Feature Animation", "a classic hand-drawn 2D feature animation frame with expressive linework and painted backgrounds"),
        ("Rubber Hose Cartoon", "a 1930s rubber hose cartoon with bendy limbs, pie-cut eyes and aged film texture"),
        ("Newspaper Comic Strip", "a black and white newspaper comic strip panel with simple linework and halftone shading"),
        ("Comic Book Panel", "a comic book panel with bold ink outlines, halftone dot shading and saturated flats"),
        ("Graphic Novel Noir", "a high-contrast black and white graphic novel panel with heavy shadow and spot blacks"),
        ("Manga Panel", "a black and white manga panel with screentone shading and dynamic speed lines"),
        ("Western Cartoon", "a modern western TV cartoon with bold clean outlines, flat colour and exaggerated shapes"),
        ("Storyboard Sketch", "a rough storyboard sketch in loose pencil with simple tonal blocking"),
        ("Concept Art", "a painterly concept art render with loose brushwork and dramatic lighting"),
        ("Character Sheet", "a character reference sheet with clean flat colour and a neutral background"),
        ("Vector Flat Illustration", "a flat vector illustration with clean geometric shapes and no gradients"),
        ("Isometric Illustration", "a clean isometric illustration with precise angles and flat shaded surfaces"),
        ("Children's Picture Book", "a warm children's picture book illustration with soft textures and gentle rounded shapes"),
        ("Editorial Illustration", "a stylised editorial illustration with limited palette and bold conceptual shapes"),
        ("Sticker Art", "a die-cut sticker illustration with a thick white border and bright saturated colour"),
        ("Chibi Style", "a chibi illustration with exaggerated mini proportions, oversized head and simple dot eyes"),
        ("Caricature", "a caricature with playfully exaggerated features drawn in confident ink and colour"),
        ("Line Art", "clean single-weight black line art on a plain white background with no shading"),
        ("Coloring Book Page", "a coloring book page with clean black outlines and completely white fill areas"),
        ("Cel-Shaded 3D", "a cel-shaded 3D render with flat banded lighting and bold outlines"),
        ("Low-Poly 3D", "a low-poly 3D render with faceted geometric surfaces and flat shading"),
        ("Voxel Art", "a voxel art render built entirely from small uniform 3D cubes"),
        ("Pixel Art", "8-bit pixel art with a limited palette, chunky square pixels and hard edges"),
        ("16-Bit Sprite", "a detailed 16-bit game sprite with rich dithered shading and a limited palette"),
        ("Claymation Frame", "a claymation stop-motion frame with molded clay texture and visible fingerprints"),
        ("Papercraft Layers", "a layered papercraft scene built from flat cut-paper shapes casting soft shadows"),
        ("Silhouette Animation", "a cut-paper silhouette animation frame with solid black shapes against a glowing background"),
    ],
    "Photography & Camera": [
        ("4K Ultra Sharp", "an ultra-sharp 4K photograph with crisp micro-detail and clean natural colour"),
        ("8K Hyper Detail", "an 8K hyper-detailed photograph with extreme texture clarity and controlled highlights"),
        ("Drone Top-Down", "a top-down aerial drone photograph looking straight down from high above"),
        ("Drone Orbit Shot", "a sweeping aerial drone shot from a high angle with the horizon visible"),
        ("Tilt-Shift Miniature", "a tilt-shift photograph where a narrow band is sharp and everything else blurs, making the scene look like a miniature model"),
        ("Long Exposure", "a long exposure photograph with smooth motion blur in moving elements and sharp static subjects"),
        ("Light Painting", "a long exposure light painting with glowing traced light trails"),
        ("Macro Detail", "an extreme macro photograph with razor-thin depth of field and visible surface texture"),
        ("Fisheye Lens", "an extreme fisheye photograph with bulbous distortion bending the edges of the frame"),
        ("Wide-Angle Environmental", "a wide-angle environmental photograph with expansive context and slight edge distortion"),
        ("Telephoto Compression", "a telephoto photograph with compressed perspective and a tightly blurred background"),
        ("Bokeh Portrait", "a portrait with creamy circular bokeh and a razor-sharp subject"),
        ("Golden Hour", "a golden hour photograph with long warm shadows and amber light leaks"),
        ("Blue Hour", "a blue hour photograph with cool dusk tones and soft ambient glow"),
        ("Overcast Soft Light", "an overcast photograph with flat shadowless diffused lighting"),
        ("Harsh Midday Sun", "a photograph in harsh direct midday sun with hard-edged shadows and bright highlights"),
        ("Film Noir", "a black and white film noir photograph with hard directional light and deep shadow"),
        ("High Contrast Monochrome", "a high contrast black and white photograph with crushed blacks and bright whites"),
        ("Sepia Vintage", "a sepia-toned vintage photograph with warm brown tones and aged edges"),
        ("Cross-Processed Film", "a cross-processed film photograph with shifted colours and blown highlights"),
        ("Lomography", "a lomography photograph with heavy vignetting, saturated colour shifts and light leaks"),
        ("Double Exposure", "a double exposure photograph where a second image blends through the subject's silhouette"),
        ("Infrared Photography", "an infrared photograph where foliage turns white and skies go dark"),
        ("HDR Photography", "a high dynamic range photograph with lifted shadows and heavily detailed highlights"),
        ("Anamorphic Widescreen", "an anamorphic widescreen cinematic frame with horizontal lens flares and oval bokeh"),
        ("35mm Film Grain", "a 35mm film photograph with natural grain, soft highlight roll-off and muted colour"),
        ("Instant Photo", "an instant camera photograph with a white border, soft focus and shifted pastel colour"),
        ("Daguerreotype", "an early daguerreotype with a silver-plated sheen, scratches and high contrast"),
        ("Tintype", "a wet-plate tintype photograph with chemical edge artifacts and shallow tonal range"),
        ("Disposable Camera", "a disposable camera snapshot with harsh direct flash, grain and washed colour"),
        ("Security Camera", "a grainy overhead security camera still with timestamp overlay and low colour fidelity"),
        ("Dashcam Footage", "a wide dashcam still with lens distortion, timestamp overlay and blown highlights"),
        ("Underwater Photography", "an underwater photograph with blue-green colour cast, floating particles and caustic light"),
        ("Thermal Imaging", "a thermal camera image mapping heat to a blue-to-white gradient"),
        ("Night Vision", "a green-tinted night vision image with heavy sensor noise and glowing highlights"),
        ("X-Ray Scan", "an X-ray scan showing internal structure in translucent greyscale"),
    ],
    "Digital & Glitch": [
        ("Glitch Art", "glitch art with corrupted digital artifacts, displaced scanlines and colour channel bleed"),
        ("Datamosh", "a datamoshed image where blocks smear and bleed into each other"),
        ("Pixel Sorting", "a pixel-sorted image where bands of pixels stretch and reorder by brightness"),
        ("VHS Tape", "a worn VHS still with tracking errors, chromatic aberration and a warm fuzzy glow"),
        ("CRT Monitor", "a CRT monitor capture with visible scanlines, screen curvature and phosphor glow"),
        ("Vaporwave", "a vaporwave composition with neon pastel overlays and heavy magenta and teal grading"),
        ("Cyberpunk Neon", "a cyberpunk scene with rain-slicked reflections and blinding neon signage"),
        ("Holographic Foil", "a holographic foil surface with iridescent rainbow shifts and metallic sheen"),
        ("Chromatic Aberration", "an image with heavy chromatic aberration splitting colour channels at the edges"),
        ("ASCII Art", "ASCII art rendered entirely from monospaced text characters"),
        ("Dot Matrix Print", "a dot matrix printout with visible pin dots and banded rows"),
        ("Thermal Receipt Print", "a thermal receipt printout in dithered black on off-white paper"),
        ("Blueprint", "a technical blueprint with white line work on deep cyan paper"),
        ("Wireframe Render", "a 3D wireframe render showing only edges and vertices on a dark background"),
        ("Topographic Map", "a topographic map with layered contour lines and elevation shading"),
        ("Circuit Board", "a printed circuit board layout with copper traces and solder pads"),
        ("Falling Code", "a dark screen of falling green monospace characters forming the image"),
        ("Deep-Fried Meme", "a deep-fried image with extreme contrast, oversaturation and blocky compression"),
        ("JPEG Compression", "a heavily compressed JPEG with visible blocking artifacts and colour banding"),
        ("Kaleidoscope", "a kaleidoscope composition with radial mirrored symmetry"),
        ("Fractal Recursion", "a fractal composition where the image repeats infinitely within itself"),
        ("Liquid Distortion", "a liquid distortion where the surface ripples and warps like disturbed water"),
        ("Heat Map", "a heat map visualisation mapping intensity to a blue-to-red gradient"),
        ("Duotone", "a duotone image built from just two contrasting colours"),
        ("Neon Outline", "a glowing neon tube outline of the subject against a dark background"),
        ("Hologram Projection", "a translucent blue hologram projection with scanline flicker and edge glow"),
        ("Point Cloud Scan", "a 3D point cloud scan built from thousands of small floating dots"),
        ("Vector Trace", "a hard-edged vector trace with posterised flat colour regions"),
    ],
    "Art Movements": [
        ("Renaissance Oil", "a Renaissance oil painting with balanced composition, soft modelling and warm varnished tone"),
        ("Baroque Chiaroscuro", "a Baroque painting with dramatic chiaroscuro, deep shadow and a single strong light source"),
        ("Rococo", "a Rococo painting with pastel colour, ornate detail and playful light"),
        ("Neoclassical", "a Neoclassical painting with crisp draughtsmanship, restrained colour and sculptural form"),
        ("Romanticism", "a Romantic painting with dramatic sky, emotional atmosphere and sweeping scale"),
        ("Impressionist", "an Impressionist painting with broken brushstrokes and shimmering natural light"),
        ("Post-Impressionist", "a Post-Impressionist painting with bold expressive colour and swirling directional strokes"),
        ("Pointillism", "a pointillist painting built entirely from small distinct dots of pure colour"),
        ("Fauvism", "a Fauvist painting with wild non-naturalistic colour and loose bold strokes"),
        ("Expressionism", "an Expressionist painting with distorted form and raw emotional colour"),
        ("Cubism", "a Cubist composition fracturing the subject into overlapping geometric planes"),
        ("Futurism", "a Futurist composition with repeated forms suggesting speed and motion"),
        ("Surrealism", "a Surrealist composition with dreamlike impossible juxtapositions"),
        ("Dada Collage", "a Dada photomontage with cut-and-pasted fragments and mismatched scale"),
        ("Bauhaus", "a Bauhaus composition with primary colours, clean geometry and functional layout"),
        ("Constructivist Poster", "a Constructivist poster with bold diagonals, red and black palette and heavy type blocks"),
        ("De Stijl", "a De Stijl composition of black grid lines and primary colour rectangles"),
        ("Art Nouveau", "an Art Nouveau illustration with whiplash curves, floral framing and flat decorative colour"),
        ("Art Deco", "an Art Deco composition with bold geometric linework and metallic gold and teal"),
        ("Pop Art", "a Pop Art treatment with flat bold colour, thick outlines and halftone dots"),
        ("Op Art", "an Op Art composition with high-contrast geometric patterns creating visual vibration"),
        ("Abstract Expressionism", "an Abstract Expressionist painting with gestural sweeping strokes and layered colour"),
        ("Minimalism", "a minimalist composition with flat colour, simple shapes and generous empty space"),
        ("Brutalist Graphic", "a brutalist graphic treatment with raw type, harsh contrast and blunt layout"),
        ("Ukiyo-e", "an ukiyo-e woodblock print with flat colour zones, strong outlines and stylised waves and clouds"),
        ("Chinese Ink Painting", "a traditional Chinese ink painting with fluid brushwork and generous empty space"),
        ("Persian Miniature", "a Persian miniature with flat perspective, ornate patterning and jewel-like colour"),
        ("Mughal Miniature", "a Mughal miniature with fine detail, gold accents and formal composition"),
        ("Madhubani", "a Madhubani painting with dense linear patterning and bold natural pigments"),
        ("Warli Art", "a Warli painting with simple white stick figures on an earthen red-brown ground"),
        ("Illuminated Manuscript", "a medieval illuminated manuscript page with gold leaf, ornate borders and flat figures"),
        ("Vintage Travel Poster", "a mid-century travel poster with flat screen-printed colour and bold simplified shapes"),
    ],
    "Scene & Setting": [
        ("Outer Space", "floating in outer space with stars, nebula colour and rim lighting from a distant sun"),
        ("Underwater Scene", "submerged underwater with caustic light, floating particles and a blue-green cast"),
        ("Dense Jungle", "deep in a dense humid jungle with layered foliage and dappled light"),
        ("Desert Dunes", "standing in vast desert dunes under a hot hazy sky"),
        ("Snowy Landscape", "in a quiet snowy landscape with falling snow and soft cold light"),
        ("Heavy Rain", "in heavy rain with wet reflective surfaces and visible falling droplets"),
        ("Thick Fog", "surrounded by thick fog that fades everything into soft grey depth"),
        ("Autumn Forest", "in an autumn forest with warm falling leaves and golden backlight"),
        ("Cherry Blossom Season", "beneath blooming cherry blossom trees with drifting petals"),
        ("Cyberpunk City", "on a rain-slicked cyberpunk street lit by dense neon signage"),
        ("Medieval Village", "in a muddy medieval village with timber buildings and overcast light"),
        ("Post-Apocalyptic Ruins", "in overgrown post-apocalyptic ruins reclaimed by moss and vines"),
        ("Floating Island", "on a floating island suspended in an open sky with clouds below"),
        ("Snow Globe", "sealed inside a glass snow globe with swirling glitter and a curved reflection"),
        ("Miniature Diorama", "as a handcrafted miniature diorama in a small lit display box"),
        ("Museum Exhibit", "displayed as a museum exhibit behind glass with a small placard and spotlighting"),
        ("Postage Stamp", "printed as a postage stamp with perforated edges and engraved detail"),
        ("Banknote Engraving", "engraved as banknote artwork with fine guilloche line work"),
        ("Magazine Cover", "as a glossy magazine cover with masthead, cover lines and studio lighting"),
        ("Movie Poster", "as a dramatic movie poster with strong key lighting and space for a title treatment"),
        ("Album Cover", "as a square album cover with bold graphic treatment and room for type"),
        ("Trading Card", "as a collectible trading card with a decorative border and stat panel"),
        ("Wanted Poster", "as an aged wanted poster on weathered parchment with woodblock type"),
        ("Vintage Advertisement", "as a mid-century printed advertisement with flat colour and retro typography"),
        ("Loading Screen", "as a stylised video game loading screen with a title treatment and progress bar"),
        ("Billboard Mockup", "displayed on a large city billboard photographed from street level"),
        ("Storefront Window", "reflected in a storefront window with subtle street reflections layered over it"),
        ("Rooftop at Night", "on a city rooftop at night with the skyline glowing behind"),
    ],
    "Portrait Makeover": [
        ("Professional Headshot", "a clean professional headshot with soft studio lighting and a neutral background"),
        ("Corporate Portrait", "a polished corporate portrait with even lighting and a blurred office background"),
        ("Passport Photo", "a formal passport photo with flat even lighting against a plain light background"),
        ("Yearbook Portrait", "a retro yearbook portrait with a mottled studio backdrop and soft warm lighting"),
        ("Royal Oil Portrait", "a formal royal oil portrait with rich fabrics, dark background and dramatic side light"),
        ("Marble Bust", "a carved white marble bust with polished stone surfaces and soft gallery lighting"),
        ("Bronze Statue", "a weathered bronze statue with green patina and hard outdoor light"),
        ("Wax Figure", "a lifelike wax museum figure with slightly waxy skin sheen under warm spotlights"),
        ("Action Figure", "a poseable action figure sealed in blister packaging with a printed cardback"),
        ("Vinyl Collectible", "a big-headed stylised vinyl collectible figure with simplified features and glossy finish"),
        ("Toy Brick Minifigure", "a small plastic toy brick minifigure with cylindrical head and printed face"),
        ("Plush Toy", "a soft stuffed plush toy with visible stitching and fabric texture"),
        ("Gingerbread Figure", "a decorated gingerbread figure with icing details on a baking tray"),
        ("Balloon Sculpture", "a twisted balloon sculpture with glossy inflated segments"),
        ("Tattoo Design", "a bold traditional tattoo design with heavy outlines and a limited ink palette"),
        ("Superhero", "a costumed superhero with dramatic rim lighting and a heroic stance"),
        ("Astronaut", "an astronaut in a detailed white spacesuit with a reflective visor"),
        ("Medieval Knight", "an armoured medieval knight with battle-worn plate and an overcast sky"),
        ("Samurai", "a samurai in layered lacquered armour with a muted traditional palette"),
        ("Cowboy", "a dusty frontier cowboy with a wide-brimmed hat and warm low sun"),
        ("Pirate Captain", "a weathered pirate captain with a long coat and sea spray in the air"),
        ("Wizard", "a robed wizard with glowing arcane light and drifting embers"),
        ("Steampunk Inventor", "a steampunk inventor with brass goggles, leather straps and clockwork detail"),
        ("Cyberpunk Netrunner", "a cyberpunk netrunner with subtle chrome implants and neon underlighting"),
        ("Renaissance Noble", "a Renaissance noble in period dress with warm varnished tones"),
        ("1920s Portrait", "a 1920s studio portrait with soft focus, art deco styling and sepia warmth"),
        ("1970s Film Portrait", "a 1970s film portrait with warm faded colour, soft grain and natural light"),
        ("Fashion Editorial", "a high-fashion editorial portrait with dramatic styling and hard studio light"),
    ],
    "Material & Sculpture": [
        ("Made of Glass", "sculpted from clear glass with refractive highlights and internal reflections"),
        ("Made of Ice", "carved from clear ice with frosted edges and cold internal glow"),
        ("Made of Marble", "carved from veined white marble with polished surfaces"),
        ("Made of Bronze", "cast in bronze with warm metallic sheen and aged patina"),
        ("Made of Gold", "cast in polished gold with mirror-bright reflective highlights"),
        ("Made of Wood", "carved from wood with visible grain, knots and tool marks"),
        ("Made of Paper", "folded and cut from layered paper with soft shadows between the layers"),
        ("Made of Fabric", "sewn from stitched fabric panels with visible seams and cloth texture"),
        ("Made of Yarn", "knitted from thick soft yarn with visible loops and fibre fuzz"),
        ("Made of Clay", "modelled from soft clay with visible fingerprints and tool marks"),
        ("Made of Chocolate", "moulded from glossy tempered chocolate with soft sheen"),
        ("Made of Candy", "formed from translucent boiled sugar candy in bright colours"),
        ("Made of Smoke", "formed from drifting wisps of smoke against a dark background"),
        ("Made of Water", "formed from clear flowing water with splash detail and refraction"),
        ("Made of Fire", "formed from living flame with glowing embers and heat haze"),
        ("Made of Lightning", "formed from crackling electric arcs against a dark sky"),
        ("Made of Crystal", "grown from faceted translucent crystal with prismatic light scatter"),
        ("Made of Sand", "sculpted from packed damp sand with granular surface texture"),
        ("Made of Metal Wire", "bent from continuous thin metal wire casting linear shadows"),
        ("Made of Stone", "carved from rough weathered stone with chisel marks and moss"),
        ("Made of Neon Tubes", "bent from glowing neon tubing mounted on a dark wall"),
        ("Made of Origami", "folded from a single sheet of crisp origami paper with clean creases"),
    ],
    "Practical Edits": [
        ("White Background Product", "a clean e-commerce product photo on a pure white background with soft even lighting"),
        ("Lifestyle Product Shot", "a lifestyle product photo staged in a natural setting with warm ambient light"),
        ("Food Photography", "an appetising food photograph with soft directional light and shallow depth of field"),
        ("Real Estate Interior", "a bright wide-angle real estate interior with corrected verticals and balanced windows"),
        ("Virtual Staging", "an empty interior furnished with tasteful modern furniture matched to the room's lighting"),
        ("Background Removal", "a cutout of the subject cleanly isolated on a transparent background with crisp edges"),
        ("Studio Backdrop", "a version of the subject placed on a seamless studio backdrop with soft even lighting"),
        ("Cinematic Color Grade", "a cinematic colour grade with teal shadows, warm skin tones and gentle contrast"),
        ("Restore Old Photo", "a restored version of a damaged photo with scratches, tears and fading repaired"),
        ("Colorize Black and White", "a naturally colourised version of a black and white photo with period-accurate tones"),
        ("Upscale and Sharpen", "an upscaled version with recovered fine detail and reduced noise"),
        ("Remove Background Clutter", "a version of the same scene with distracting background clutter cleanly removed"),
        ("Change to Golden Hour", "a version of the same scene relit as golden hour with long warm shadows"),
        ("Change to Night", "a version of the same scene shifted to night with artificial lighting and cool ambient shadow"),
        ("Change Season to Winter", "a version of the same scene shifted to winter with snow cover and bare branches"),
        ("Change Season to Autumn", "a version of the same scene shifted to autumn with warm foliage and low golden light"),
        ("Add Dramatic Sky", "a version of the same scene with a dramatic cloudy sky replacing a flat one, lighting matched"),
        ("Add Water Reflection", "a version of the same scene with a still water reflection added below, correctly mirrored"),
        ("T-Shirt Mockup", "a mockup of the image printed on a folded t-shirt photographed flat with natural fabric shadows"),
        ("Mug Mockup", "a mockup of the image wrapped onto a ceramic mug photographed on a clean surface"),
        ("Phone Screen Mockup", "a mockup of the image on a phone screen held in a hand with realistic screen reflection"),
        ("Framed Wall Art", "a mockup of the image printed and framed as wall art hanging in a softly lit room"),
    ],
}

# Wrapper phrasings, rotated so prompts don't read identically. Some categories
# need their own phrasing because their descriptors start with a participle
# ("carved from marble") or a placement ("floating in outer space") rather than
# a noun phrase — the default "transform into ..." wrapper is ungrammatical there.
DEFAULT_WRAPPERS = [
    "Transform the uploaded photo into {d}.",
    "Restyle this image as {d}.",
    "Convert the attached photo into {d}.",
    "Reimagine the uploaded image as {d}.",
    "Redraw this photo as {d}.",
    "Render the uploaded image as {d}.",
]

WRAPPERS = {
    "Scene & Setting": [
        "Restage the uploaded photo {d}.",
        "Take the subject from the uploaded photo and present it {d}.",
        "Keep the subject from this photo and place it {d}.",
    ],
    "Material & Sculpture": [
        "Recreate the subject from the uploaded photo as if it were {d}.",
        "Rebuild the subject in this photo as if {d}.",
        "Remake the subject from the uploaded image as if it were {d}.",
    ],
    "Practical Edits": [
        "Edit the uploaded photo to produce {d}.",
        "Process the uploaded image into {d}.",
        "Retouch the attached photo into {d}.",
    ],
}

# Category-specific preservation clause — the part that makes img2img work.
PRESERVE = {
    "Traditional Media": "Keep the subject's pose, proportions and facial features clearly recognisable, and preserve the original composition.",
    "Illustration & Animation": "Keep the subject's identity, pose and clothing recognisable while simplifying detail to suit the style.",
    "Photography & Camera": "Keep the subject and composition exactly as they are — change only the photographic treatment.",
    "Digital & Glitch": "Keep the underlying subject readable beneath the effect so it stays identifiable.",
    "Art Movements": "Keep the subject's pose and the overall composition intact while adopting the movement's visual language.",
    "Scene & Setting": "Keep the subject unchanged and replace only the surroundings. Match the lighting on the subject to the new environment.",
    "Portrait Makeover": "Keep the person's facial features, skin tone and expression clearly recognisable.",
    "Material & Sculpture": "Keep the silhouette, pose and proportions intact so the subject stays recognisable.",
    "Practical Edits": "Keep the subject accurate and unaltered — this is a correction, not a reinterpretation.",
}

# Stock-photo search terms, used by fetch-stock.js. Most style names work as-is;
# these are the ones where the literal name returns nothing useful.
SEARCH_OVERRIDES = {
    "4K Ultra Sharp": "ultra sharp detailed landscape",
    "8K Hyper Detail": "extremely detailed macro texture",
    "Drone Top-Down": "aerial top down view",
    "Drone Orbit Shot": "aerial drone landscape",
    "Telephoto Compression": "telephoto city street",
    "Overcast Soft Light": "overcast moody landscape",
    "Harsh Midday Sun": "harsh sunlight shadows",
    "High Contrast Monochrome": "high contrast black and white",
    "Cross-Processed Film": "retro film photography",
    "Disposable Camera": "flash party photo",
    "Security Camera": "surveillance camera view",
    "Dashcam Footage": "road view from car",
    "Anamorphic Widescreen": "cinematic widescreen scene",
    "35mm Film Grain": "35mm film photograph",
    "Instant Photo": "polaroid instant photo",
    "Falling Code": "green matrix code",
    "Deep-Fried Meme": "oversaturated glitch",
    "JPEG Compression": "pixelated compressed image",
    "Duotone": "duotone poster design",
    "Point Cloud Scan": "3d scan point cloud",
    "Vector Trace": "flat vector poster",
    "Liquid Distortion": "liquid ripple texture",
    "Heat Map": "thermal heat map",
    "Illuminated Manuscript": "medieval manuscript page",
    "Vintage Travel Poster": "vintage travel poster",
    "Constructivist Poster": "constructivist propaganda poster",
    "De Stijl": "mondrian geometric composition",
    "Op Art": "optical illusion pattern",
    "Brutalist Graphic": "brutalist concrete architecture",
    "Outer Space": "nebula stars space",
    "Snow Globe": "snow globe",
    "Miniature Diorama": "miniature model diorama",
    "Museum Exhibit": "museum display case",
    "Banknote Engraving": "banknote detail",
    "Magazine Cover": "magazine cover mockup",
    "Loading Screen": "video game screen",
    "Billboard Mockup": "city billboard",
    "Storefront Window": "shop window reflection",
    "Rooftop at Night": "city rooftop night skyline",
    "Professional Headshot": "professional headshot",
    "Corporate Portrait": "corporate business portrait",
    "Passport Photo": "passport photo",
    "Yearbook Portrait": "retro studio portrait",
    "Royal Oil Portrait": "classical oil portrait painting",
    "Action Figure": "action figure toy",
    "Vinyl Collectible": "vinyl toy figure",
    "Toy Brick Minifigure": "plastic toy figure",
    "Plush Toy": "plush stuffed toy",
    "Gingerbread Figure": "gingerbread man cookie",
    "Balloon Sculpture": "balloon animal",
    "Tattoo Design": "tattoo art design",
    "Cyberpunk Netrunner": "cyberpunk neon portrait",
    "Steampunk Inventor": "steampunk goggles",
    "Renaissance Noble": "renaissance painting portrait",
    "1920s Portrait": "1920s vintage portrait",
    "1970s Film Portrait": "1970s retro portrait",
    "Fashion Editorial": "fashion editorial portrait",
    "White Background Product": "product on white background",
    "Lifestyle Product Shot": "lifestyle product photography",
    "Real Estate Interior": "modern interior living room",
    "Virtual Staging": "staged furnished living room",
    "Background Removal": "isolated object white background",
    "Studio Backdrop": "studio portrait backdrop",
    "Cinematic Color Grade": "cinematic moody scene",
    "Restore Old Photo": "old damaged photograph",
    "Colorize Black and White": "vintage black and white photo",
    "Upscale and Sharpen": "sharp detailed portrait",
    "Remove Background Clutter": "minimal clean desk",
    "Change to Golden Hour": "golden hour landscape",
    "Change to Night": "city at night",
    "Change Season to Winter": "snowy winter landscape",
    "Change Season to Autumn": "autumn forest foliage",
    "Add Dramatic Sky": "dramatic storm clouds",
    "Add Water Reflection": "lake reflection landscape",
    "T-Shirt Mockup": "blank t-shirt mockup",
    "Mug Mockup": "plain ceramic mug",
    "Phone Screen Mockup": "phone in hand screen",
    "Framed Wall Art": "framed art on wall",
    "Hand-Painted Anime Film": "anime landscape illustration",
    "Soft Cel Animation": "cartoon illustration",
    "Classic 2D Feature Animation": "hand drawn animation art",
    "Rubber Hose Cartoon": "vintage cartoon",
    "Newspaper Comic Strip": "newspaper comic",
    "Storyboard Sketch": "storyboard sketch",
    "Character Sheet": "character design sheet",
    "Coloring Book Page": "coloring book outline",
    "Line Art": "minimal line art drawing",
    "Cel-Shaded 3D": "3d cartoon render",
    "16-Bit Sprite": "retro game pixel",
    "Silhouette Animation": "silhouette against light",
    "Claymation Frame": "clay figure model",
    "Papercraft Layers": "layered paper art",
}


def search_term(name):
    if name in SEARCH_OVERRIDES:
        return SEARCH_OVERRIDES[name]
    if name.startswith("Made of "):
        return name[len("Made of "):] + " sculpture texture"
    return name


SIZES = ["tall", "", "short", "", "tall", "short", "", ""]


def slugify(s):
    out = []
    for ch in s.lower():
        out.append(ch if ch.isalnum() else "-")
    slug = "".join(out)
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")


entries = []
i = 0
for cat, styles in CATALOG.items():
    for name, desc in styles:
        wrapper_set = WRAPPERS.get(cat, DEFAULT_WRAPPERS)
        wrapper = wrapper_set[i % len(wrapper_set)]
        prompt = wrapper.format(d=desc) + " " + PRESERVE[cat]
        entries.append({
            "style": name,
            "cat": cat,
            "size": SIZES[i % len(SIZES)],
            "prompt": prompt,
            "slug": slugify(name),
            "search": search_term(name),
        })
        i += 1

# sanity checks
slugs = [e["slug"] for e in entries]
assert len(slugs) == len(set(slugs)), "duplicate slug: " + str(
    [s for s in slugs if slugs.count(s) > 1][:5]
)
names = [e["style"] for e in entries]
assert len(names) == len(set(names)), "duplicate style name"

lines = [
    "/* ==================================================================",
    "   prompts-image.js — image-to-image transformation prompts.",
    "",
    "   These are written for an UPLOADED photo: the user supplies the image,",
    "   the prompt restyles it. That's why each one names what to preserve",
    "   (face, pose, composition) — without that, models drift off the subject.",
    "",
    "   GENERATED FILE — edit build_prompts.py and re-run instead of editing",
    "   this by hand, or your changes get overwritten:",
    "       python3 build_prompts.py",
    "",
    "   Fields: style (display name), cat (filter group), size (masonry height),",
    "   prompt (the text), slug (thumbnail filename in images/), search (stock",
    "   photo keywords for fetch-stock.js — not used by the site's own search).",
    "   ================================================================== */",
    "window.imagePrompts = [",
]
for e in entries:
    lines.append("  " + json.dumps(e, ensure_ascii=False) + ",")
lines.append("];")

# Resolve against this file rather than the shell's cwd, so running the script
# from a parent directory cannot silently drop the output somewhere else.
# newline="\n" keeps the generated file LF on every platform, not CRLF on Windows.
OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts-image.js")
with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote prompts-image.js with {len(entries)} prompts")
for cat, styles in CATALOG.items():
    print(f"  {len(styles):>3}  {cat}")
