/* ==================================================================
   DATA

   IMAGE PROMPTS now live in prompts-image.js (266 image-to-image transformation
   prompts, generated by build_prompts.py). That file sets window.imagePrompts
   and must be loaded before this one. To add or edit image prompts, edit
   build_prompts.py and re-run it — don't edit prompts-image.js by hand.
   ================================================================== */
const imagePrompts = Array.isArray(window.imagePrompts) ? window.imagePrompts : [];

/* Text prompt templates live in prompts-text.js, loaded only by the four
   category pages. Builder vocabulary lives in builder-data.js, loaded only
   by builder.html. Both are absent on most pages by design — null means
   'this page does not have it', which the inits below check for. */
const textPromptsData = window.textPromptsData || null;

/* Hero demo (index.html only) — cycles automatically, mixing image and text
   results so the hero shows both halves of the site. */
const demoPairs = [
  { type:"image", filename:"image_04.txt", model:"Midjourney", style:"Neon Noir", hue:4,
    prompt:"cyberpunk alley, neon rain reflections, cinematic wide shot, teal and magenta lighting --ar 16:9 --v 6" },
  { type:"text", filename:"email_02.txt", model:"Claude",
    prompt:"Write a confident cold email to a hiring manager about a Frontend role, under 120 words, no generic flattery.",
    result:"Subject: A tool I built that might help your onboarding flow\n\nHi Priya — I recently cut my team's deploy time in half with a small internal tool. I think something similar could streamline onboarding for new engineers on your team. Worth a quick 15-minute call this week?" },
  { type:"image", filename:"image_11.txt", model:"Midjourney", style:"Watercolor Whimsy", hue:0,
    prompt:"misty pine forest at dawn, volumetric light rays through fog, muted teal and amber palette --ar 16:9" },
  { type:"text", filename:"ppt_03.txt", model:"GPT",
    prompt:"Give me a 3-slide pitch outline for a campus food delivery startup: problem, solution, ask.",
    result:"1. Problem — students skip meals during exam week; existing delivery apps are too slow for campus routes.\n2. Solution — a 10-minute delivery network run by students, for students.\n3. Ask — seed funding to launch on 3 campuses this semester." }
];

/* ==================================================================
   ICONS — inline SVG strings, reused wherever needed. No emoji on this site.
   ================================================================== */
const ICONS = {
  copy:  '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>',
  check: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12l5 5L19 8"/></svg>',
  close: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M6 6l12 12M18 6L6 18"/></svg>',
  arrow: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M7 17L17 7M9 7h8v8"/></svg>',
  spark: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9L12 3z"/></svg>',
  ppt:    '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="12" rx="1.5"/><path d="M8 21h8M12 17v4"/></svg>',
  essay:  '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2h9l5 5v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z"/><path d="M14 2v5h5M8 13h8M8 17h5"/></svg>',
  report: '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 16v-3M12 16V8M16 16v-6"/></svg>',
  email:  '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></svg>'
};

/* Thumbnail treatment per text category — gradient + icon, so every prompt card
   has a visual anchor the same way the image cards do. */
const categoryVisuals = {
  ppt:    { icon:"ppt",    swatch:"swatch-1", label:"Presentation" },
  essay:  { icon:"essay",  swatch:"swatch-3", label:"Essay" },
  report: { icon:"report", swatch:"swatch-2", label:"Report" },
  email:  { icon:"email",  swatch:"swatch-0", label:"Email" }
};

/* ==================================================================
   HELPERS
   ================================================================== */
const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/* Correct for BOTH element text and quoted attribute values, so one function
   covers every interpolation site. The previous escapeAttr() handled only & and
   ", which left < > and ' raw — fine for today's data by luck, not by design.
   Deliberate exceptions: the ICONS constants (trusted inline SVG) and
   highlightVars(), which escapes first and then adds its own markup. */
const HTML_ESCAPES = { "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" };
function escapeHTML(value){
  return String(value == null ? "" : value).replace(/[&<>"']/g, (ch) => HTML_ESCAPES[ch]);
}

/* Escape BEFORE wrapping [placeholders], so prompt text can never introduce
   markup — this fed straight into innerHTML unescaped. Escaping leaves the
   square brackets alone, so the match still works. */
function highlightVars(str){
  return escapeHTML(str).replace(/\[([^\]]+)\]/g, '<span class="var">[$1]</span>');
}
function copyButtonHTML(label){
  return `${ICONS.copy}<span>${escapeHTML(label)}</span>`;
}
/* Fisher-Yates on a copy. Every visit surfaces a different first screen
   instead of the same handful of prompts, which is the point of a library this
   size. Callers that need stable positions must stamp their indices AFTER
   shuffling, not before. */
function shuffled(list){
  const out = list.slice();
  for(let i = out.length - 1; i > 0; i--){
    const j = Math.floor(Math.random() * (i + 1));
    const tmp = out[i];
    out[i] = out[j];
    out[j] = tmp;
  }
  return out;
}

function slugify(str){
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
/* Thumbnails are optional: images/<slug>.jpg if present (see images/README.md),
   otherwise the gradient swatch underneath shows through. Dropping the <img> on
   error is what reveals it, and avoids a broken-image icon.

   'error' does not bubble, so this captures instead — one listener covers every
   thumbnail, including ones rendered later, and replaces the inline onerror
   attributes these images used to carry.

   NB: the previous helper here described a local -> stock photo -> swatch chain.
   No such chain existed; nothing ever called it and no fallback URL was ever
   set. fetch-stock.js downloads stock photos INTO images/ ahead of time, so at
   runtime there is only ever the one source. */
document.addEventListener("error", (e) => {
  const img = e.target;
  if(img instanceof HTMLImageElement && img.classList.contains("real-photo")) img.remove();
}, true);

let revealObserver;
function observeReveals(){
  /* No IntersectionObserver means nothing would ever add .in-view, and the
     elements are already hidden by .js .reveal — so reveal them outright
     rather than leaving the page blank. */
  if(!("IntersectionObserver" in window)){
    document.querySelectorAll(".reveal:not(.in-view)").forEach((el) => el.classList.add("in-view"));
    return;
  }
  if(!revealObserver){
    revealObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if(entry.isIntersecting){
          entry.target.classList.add("in-view");
          revealObserver.unobserve(entry.target);
        }
      });
    }, { threshold:0.15 });
  }
  document.querySelectorAll(".reveal:not(.in-view)").forEach((el) => revealObserver.observe(el));
}

/* Screen-reader announcements. One shared polite live region, created lazily so
   pages that never announce anything don't carry the node. */
let liveRegion;
function announce(message){
  if(!liveRegion){
    liveRegion = document.createElement("div");
    liveRegion.className = "sr-only";
    liveRegion.setAttribute("role", "status");
    liveRegion.setAttribute("aria-live", "polite");
    document.body.appendChild(liveRegion);
  }
  /* Clear first, or repeating the same string is not re-announced. */
  liveRegion.textContent = "";
  setTimeout(() => { liveRegion.textContent = message; }, 60);
}

/* Pre-async-clipboard fallback. navigator.clipboard is undefined on every
   non-secure origin, which includes opening these pages straight off the
   filesystem — a supported way to use this site — so this path is not exotic. */
function legacyCopy(text){
  const ta = document.createElement("textarea");
  ta.value = text;
  ta.setAttribute("readonly", "");
  /* Off-screen, not display:none — execCommand needs a real selection. */
  ta.style.cssText = "position:fixed;top:0;left:-9999px;opacity:0;";
  document.body.appendChild(ta);

  let ok = false;
  try {
    ta.select();
    ta.setSelectionRange(0, ta.value.length);
    ok = document.execCommand("copy");
  } catch(err){
    ok = false;
  }
  ta.remove();
  return ok;
}

function flashCopyResult(btn, ok){
  if(btn.dataset.copyBusy) return;
  btn.dataset.copyBusy = "1";

  const original = btn.innerHTML;
  btn.innerHTML = ok
    ? `${ICONS.check}<span>Copied!</span>`
    : `${ICONS.close}<span>Copy failed</span>`;
  btn.classList.add(ok ? "copied" : "copy-failed");
  announce(ok ? "Prompt copied to clipboard" : "Copy failed — select the prompt text and copy it manually");

  setTimeout(() => {
    btn.innerHTML = original;
    btn.classList.remove("copied", "copy-failed");
    delete btn.dataset.copyBusy;
  }, ok ? 1600 : 2800);
}

/* Async clipboard where it exists, textarea fallback where it doesn't, and a
   visible failure state if both are refused — previously a rejected promise or
   a missing API produced no feedback at all. */
function copyText(text, btn){
  if(navigator.clipboard && window.isSecureContext){
    navigator.clipboard.writeText(text).then(
      () => flashCopyResult(btn, true),
      () => flashCopyResult(btn, legacyCopy(text))
    );
    return;
  }
  flashCopyResult(btn, legacyCopy(text));
}

/* ==================================================================
   COUNT-UP STATS (index.html)

   Runs when the figure scrolls into view, once. Eases out so it decelerates
   into the final number instead of arriving at a constant rate, and writes
   through requestAnimationFrame rather than setInterval so it stays on the
   compositor's clock.
   ================================================================== */
function initCountUp(){
  const figures = document.querySelectorAll("[data-count-to]");
  if(!figures.length) return;

  const render = (el, value) => {
    const prefix = el.dataset.countPrefix || "";
    el.textContent = prefix + value.toLocaleString();
  };

  /* Reduced motion: no tally, just the number. */
  if(prefersReducedMotion || !("IntersectionObserver" in window)){
    figures.forEach((el) => render(el, Number(el.dataset.countTo)));
    return;
  }

  const run = (el) => {
    const target = Number(el.dataset.countTo) || 0;
    if(target === 0){ render(el, 0); return; }

    const duration = 1100;
    let start = null;
    const step = (now) => {
      if(start === null) start = now;
      const t = Math.min((now - start) / duration, 1);
      /* easeOutExpo — fast off the mark, long settle. */
      const eased = t === 1 ? 1 : 1 - Math.pow(2, -10 * t);
      render(el, Math.round(target * eased));
      if(t < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  };

  const io = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if(!entry.isIntersecting) return;
      io.unobserve(entry.target);
      run(entry.target);
    });
  }, { threshold: 0.4 });

  figures.forEach((el) => io.observe(el));
}

/* ==================================================================
   SEND TO AN ASSISTANT

   ChatGPT accepts a ?q= prefill; Gemini has no documented equivalent, so
   opening it lands on an empty composer. Both buttons therefore copy the
   prompt FIRST and open second — paste works regardless of whether the
   destination honours a parameter, and the behaviour is identical either
   way from the visitor's side.
   ================================================================== */
const SEND_TARGETS = [
  {
    id: "chatgpt",
    label: "ChatGPT",
    /* Prefills the composer. Prompts here top out around 540 characters, so
       the encoded URL stays far inside every browser's length limit. */
    url: (prompt) => `https://chatgpt.com/?q=${encodeURIComponent(prompt)}`,
    icon: `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.2 20 7.6v8.8L12 20.8 4 16.4V7.6z"/><path d="M12 12v8.8M12 12 4 7.6M12 12l8-4.4"/></svg>`
  },
  {
    id: "gemini",
    label: "Gemini",
    url: () => "https://gemini.google.com/app",
    icon: `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3c.5 4.3 2.7 6.5 7 7-4.3.5-6.5 2.7-7 7-.5-4.3-2.7-6.5-7-7 4.3-.5 6.5-2.7 7-7z"/></svg>`
  }
];

function sendRowHTML(prompt){
  return SEND_TARGETS.map((t) =>
    `<button type="button" class="btn btn-ghost btn-sm btn-send" data-send="${t.id}" data-raw="${escapeHTML(prompt)}">${t.icon}<span>Open in ${escapeHTML(t.label)}</span></button>`
  ).join("");
}

/* Delegated: a category page renders 114 cards, so per-button listeners meant
   228 of them re-attached on every filter and every debounced keystroke. One
   listener on the container survives innerHTML replacement of its children. */
function bindSendButtons(root){
  if(root.dataset.sendBound) return;
  root.dataset.sendBound = "1";

  root.addEventListener("click", (e) => {
    const btn = e.target.closest(".btn-send");
    if(!btn || !root.contains(btn)) return;

    const target = SEND_TARGETS.find((t) => t.id === btn.dataset.send);
    if(!target) return;
    const prompt = btn.dataset.raw || "";

    /* Opened synchronously, inside the click, or a popup blocker rejects it —
       an await before this point loses the user-gesture context. */
    const win = window.open(target.url(prompt), "_blank", "noopener,noreferrer");

    copyText(prompt, btn);

    /* copyText announces its own result on a short timer; delay this so the
       two messages queue rather than clobbering each other. */
    if(!win){
      setTimeout(() => announce("The new tab was blocked, but the prompt is copied — paste it into " + target.label + "."), 240);
    }
  });
}

/* ==================================================================
   NAV — active link, mobile toggle (runs on every page)
   ================================================================== */
function setActiveNav(){
  let file = location.pathname.split("/").pop();
  if(file === "") file = "index.html";
  const textGroup = ["text.html","ppt.html","essay.html","report.html","email.html"];
  document.querySelectorAll(".nav-link").forEach((link) => {
    const target = link.dataset.page;
    const isActive = target === file || (target === "text.html" && textGroup.includes(file));
    link.classList.toggle("active", isActive);
  });
}

/* Dark is the default and the site's identity; the toggle is an override that
   persists per browser. The stored value is applied by the inline bootstrap in
   <head> so the page never paints one theme then swaps to the other. */
function initThemeToggle(){
  const btn = document.getElementById("themeToggle");
  if(!btn) return;

  const current = () => document.documentElement.getAttribute("data-theme") === "light" ? "light" : "dark";

  /* Paint the swap over --dur-3 instead of flashing. The class is removed once
     the transition has run, so no element keeps an all-properties transition. */
  let fadeTimer;
  const crossFade = () => {
    const root = document.documentElement;
    root.classList.add("theme-transition");
    clearTimeout(fadeTimer);
    fadeTimer = setTimeout(() => root.classList.remove("theme-transition"), 400);
  };

  const apply = (theme) => {
    document.documentElement.setAttribute("data-theme", theme);
    /* role=switch, so state is aria-checked. The label names what the switch
       controls, not what pressing it would do — the state carries that. */
    btn.setAttribute("aria-checked", String(theme === "light"));
    btn.setAttribute("aria-label", "Light theme");
  };

  apply(current());

  btn.addEventListener("click", () => {
    const next = current() === "light" ? "dark" : "light";
    crossFade();
    apply(next);
    try {
      localStorage.setItem("promptlib-theme", next);
    } catch(err){
      /* Storage can throw in private mode. The switch still works for this
         page; it just will not be remembered. */
    }
    announce(next === "light" ? "Light theme enabled" : "Dark theme enabled");
  });
}

/* Slides one shared pill behind the nav links instead of giving each link its
   own background. Only transform and width animate, both composited, so
   moving between links never costs layout on the links themselves.

   The active link is already styled by weight and colour, so if this never
   runs — JS off, or a viewport where the indicator is display:none — the nav
   still reads correctly. */
function initNavIndicator(){
  const row = document.getElementById("navLinks");
  const bar = document.getElementById("navIndicator");
  if(!row || !bar) return;

  const active = () => row.querySelector(".nav-link.active");

  const moveTo = (link) => {
    if(!link) return;
    /* display:none on mobile — offsetParent is null, nothing to position. */
    if(!bar.offsetParent) return;
    bar.style.width = `${link.offsetWidth}px`;
    bar.style.transform = `translate3d(${link.offsetLeft - row.clientLeft}px,0,0)`;
    bar.classList.add("is-ready");
  };

  const settle = () => moveTo(active());

  /* Fonts land after first paint and change link widths, so measure again
     once they are ready rather than freezing a stale position. */
  settle();
  if(document.fonts && document.fonts.ready) document.fonts.ready.then(settle);

  row.querySelectorAll(".nav-link").forEach((link) => {
    link.addEventListener("mouseenter", () => moveTo(link));
    link.addEventListener("focus", () => moveTo(link));
  });
  row.addEventListener("mouseleave", settle);
  row.addEventListener("focusout", (e) => {
    if(!row.contains(e.relatedTarget)) settle();
  });

  let resizeTimer;
  window.addEventListener("resize", () => {
    /* No transition while the layout is still moving under it. */
    bar.style.transition = "none";
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => { bar.style.transition = ""; settle(); }, 100);
    settle();
  });
}

/* The nav is borderless until something scrolls under it. Passive listener and
   a class toggle only — no style writes per frame. */
function initNavScrollState(){
  const nav = document.querySelector(".nav");
  if(!nav) return;
  let ticking = false;
  const update = () => {
    nav.classList.toggle("is-scrolled", window.scrollY > 4);
    ticking = false;
  };
  update();
  window.addEventListener("scroll", () => {
    if(ticking) return;
    ticking = true;
    requestAnimationFrame(update);
  }, { passive: true });
}

function initMobileNav(){
  const navToggle = document.getElementById("navToggle");
  const navLinksEl = document.getElementById("navLinks");
  if(!navToggle || !navLinksEl) return;
  navToggle.addEventListener("click", () => {
    const isOpen = navLinksEl.classList.toggle("open");
    navToggle.classList.toggle("open", isOpen);
    navToggle.setAttribute("aria-expanded", String(isOpen));
  });
}

/* ==================================================================
   PAGE TRANSITIONS — fade in on load, fade out before internal navigation
   ================================================================== */
function initPageTransitions(){
  requestAnimationFrame(() => requestAnimationFrame(() => document.body.classList.add("loaded")));

  document.addEventListener("click", (e) => {
    /* Anything that is not a plain left-click belongs to the browser: modifier
       clicks open new tabs or windows, and middle-click arrives as auxclick. */
    if(e.defaultPrevented || e.button !== 0) return;
    if(e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;

    const link = e.target.closest("a");
    if(!link || link.target === "_blank" || link.hasAttribute("download")) return;

    const href = link.getAttribute("href");
    if(!href || href.startsWith("#")) return;

    /* Only relative in-site navigations get the fade. Any href carrying an
       explicit scheme — http:, mailto:, tel:, data:, blob: — is left alone.
       data: matters: browsers refuse top-level data: navigation, so routing the
       builder's Download link through window.location silently did nothing. */
    if(href.startsWith("//") || /^[a-z][a-z0-9+.-]*:/i.test(href)) return;

    e.preventDefault();
    document.body.classList.remove("loaded");
    document.body.classList.add("leaving");
    setTimeout(() => { window.location.href = href; }, prefersReducedMotion ? 0 : 260);
  });
}

/* ==================================================================
   IMAGE GALLERY + MODAL (images.html only)
   ================================================================== */
let galleryState = { cat: "All", query: "" };

/* ---- URL state -------------------------------------------------------
   Filters live in the query string, so a filtered view can be linked, shared
   and bookmarked, and Back undoes a filter instead of leaving the page.

   Category changes push a history entry: they are discrete, deliberate acts,
   and Back undoing them is exactly what people expect. Typing only replaces
   the current entry — pushing per debounced keystroke would bury the previous
   page under a dozen near-identical entries. Say the word if you would rather
   search be pushed too. */
function syncUrl(push){
  const search = document.getElementById("gallerySearch");
  const params = new URLSearchParams();
  if(galleryState.cat !== "All") params.set("cat", galleryState.cat);
  const raw = search ? search.value.trim() : "";
  if(raw) params.set("q", raw);

  const qs = params.toString();
  const url = qs ? `?${qs}` : location.pathname;
  try {
    history[push ? "pushState" : "replaceState"](null, "", url);
  } catch(err){
    /* Some browsers reject history manipulation on file:// origins. Opening
       the page straight off disk is supported, so degrade quietly: the
       filters still work, they just are not linkable there. */
  }
}

function readStateFromUrl(){
  const params = new URLSearchParams(location.search);
  const cat = params.get("cat") || "All";
  /* A category that is not in the data — a stale link, a typo, a renamed
     category in build_prompts.py — falls back to All rather than rendering an
     empty grid the visitor cannot explain. */
  galleryState.cat = (cat === "All" || imagePrompts.some((p) => p.cat === cat)) ? cat : "All";

  const raw = params.get("q") || "";
  const search = document.getElementById("gallerySearch");
  if(search) search.value = raw;
  galleryState.query = raw.trim().toLowerCase();
}

/* Push the state we just read back onto the controls, for first load and for
   Back/Forward, where the chips and the search box are otherwise stale. */
function syncControlsToState(){
  const chipRow = document.getElementById("galleryChips");
  if(chipRow){
    chipRow.querySelectorAll(".chip").forEach((c) => {
      const on = c.dataset.cat === galleryState.cat;
      c.classList.toggle("active", on);
      c.setAttribute("aria-pressed", String(on));
    });
  }
}

/* prompts-image.js is a separate <script>; if it 404s, is blocked, or fails to
   parse, we arrive here with nothing. Say that plainly — an empty grid plus
   "no prompts match that search" blames the visitor for a load failure. */
function renderGalleryUnavailable(){
  const grid = document.getElementById("galleryGrid");
  const countEl = document.getElementById("galleryCount");
  const chipRow = document.getElementById("galleryChips");
  const search = document.getElementById("gallerySearch");

  if(countEl) countEl.textContent = "unavailable";
  if(chipRow) chipRow.innerHTML = "";
  if(search){
    search.disabled = true;
    search.placeholder = "Search unavailable";
  }

  grid.innerHTML = `
    <div class="gallery-error" role="alert">
      <p class="gallery-error-title">The prompt library didn&rsquo;t load.</p>
      <p>prompts-image.js is missing or failed to parse, so there is nothing to show.
      Try reloading. If it keeps happening, regenerate it with
      <code>python3 build_prompts.py</code>.</p>
    </div>`;
}

function initGallery(){
  const grid = document.getElementById("galleryGrid");
  if(!grid) return;

  if(!imagePrompts.length){
    renderGalleryUnavailable();
    return;
  }

  /* Shuffle first, THEN stamp. p.i is the position in imagePrompts, which the
     modal and the swatch colour both index by, so the stamp has to describe the
     array as it now stands. Reordering after stamping would desync them. */
  const order = shuffled(imagePrompts);
  imagePrompts.length = 0;
  imagePrompts.push(...order);
  imagePrompts.forEach((p, i) => { p.i = i; });

  /* Category chips are derived from the data, so adding a new category in
     build_prompts.py makes a new filter appear with no edit here. */
  const cats = ["All", ...new Set(imagePrompts.map((p) => p.cat))];
  const chipRow = document.getElementById("galleryChips");
  chipRow.innerHTML = cats.map((c) =>
    `<button type="button" class="chip${c === "All" ? " active" : ""}" data-cat="${escapeHTML(c)}" aria-pressed="${c === "All"}">${escapeHTML(c)}</button>`
  ).join("");

  chipRow.querySelectorAll(".chip").forEach((chip) => {
    chip.addEventListener("click", () => {
      /* aria-pressed tracks .active so the selected filter is announced, not
         just coloured — the class alone tells assistive tech nothing. */
      chipRow.querySelectorAll(".chip").forEach((c) => {
        c.classList.remove("active");
        c.setAttribute("aria-pressed", "false");
      });
      chip.classList.add("active");
      chip.setAttribute("aria-pressed", "true");
      galleryState.cat = chip.dataset.cat;
      syncUrl(true);
      renderGallery();
    });
  });

  /* Coalesce keystrokes. Each render rebuilds all 266 cards and re-runs the
     IntersectionObserver over them, so firing per character made fast typing
     do that work a dozen times to show one result. 120ms is below the point
     where the list feels laggy but well above burst typing. */
  const search = document.getElementById("gallerySearch");
  /* The count in the placeholder is hardcoded in images.html as a no-JS
     fallback; take it from the data so it cannot drift when build_prompts.py
     gains or loses styles. */
  search.placeholder = search.placeholder.replace(/\d+/, imagePrompts.length);
  let searchTimer;
  const applySearch = () => {
    const next = search.value.trim().toLowerCase();
    if(next === galleryState.query) return;
    galleryState.query = next;
    syncUrl(false);
    renderGallery();
  };
  search.addEventListener("input", () => {
    clearTimeout(searchTimer);
    searchTimer = setTimeout(applySearch, 120);
  });
  /* Enter and the type=search clear button should feel immediate. */
  search.addEventListener("search", () => { clearTimeout(searchTimer); applySearch(); });
  search.addEventListener("keydown", (e) => {
    if(e.key === "Enter"){ clearTimeout(searchTimer); applySearch(); }
  });

  const modalCloseBtn = document.getElementById("modalClose");
  const modalBackdrop = document.getElementById("modalBackdrop");
  const modalCopyBtn = document.getElementById("modalCopyBtn");
  modalCloseBtn.innerHTML = ICONS.close;
  modalCopyBtn.innerHTML = copyButtonHTML("Copy prompt");

  modalCloseBtn.addEventListener("click", closeModal);
  modalBackdrop.addEventListener("click", (e) => { if(e.target === modalBackdrop) closeModal(); });
  modalCopyBtn.addEventListener("click", function(){ copyText(this.dataset.raw, this); });

  /* Adopt whatever the incoming URL asked for before the first paint. */
  readStateFromUrl();
  syncControlsToState();

  window.addEventListener("popstate", () => {
    closeModal();
    readStateFromUrl();
    syncControlsToState();
    renderGallery();
  });

  renderGallery();
}

function filteredPrompts(){
  return imagePrompts.filter((p) => {
    if(galleryState.cat !== "All" && p.cat !== galleryState.cat) return false;
    if(!galleryState.query) return true;
    return (p.style + " " + p.cat + " " + p.prompt).toLowerCase().includes(galleryState.query);
  });
}

function renderGallery(){
  const grid = document.getElementById("galleryGrid");
  const countEl = document.getElementById("galleryCount");
  const list = filteredPrompts();

  countEl.textContent = `${list.length} prompt${list.length === 1 ? "" : "s"}`;

  if(!list.length){
    grid.innerHTML = `<p class="gallery-empty">No prompts match that search. Try a different word, or pick another category.</p>`;
    return;
  }

  /* Which thumbnails actually exist, per images/manifest.js (generated by
     build-manifest.js). Emitting <img> for all 266 meant 266 404s on any
     deploy without thumbnails, which is the default since images/ is
     gitignored. If the manifest is absent we stay optimistic and emit them
     all, so deleting it degrades to the old behaviour rather than hiding
     images someone placed by hand. */
  const manifest = window.imageManifest;
  const known = Array.isArray(manifest) ? new Set(manifest) : null;
  const hasThumb = (slug) => known === null || known.has(slug);

  /* p.i (stamped in initGallery) is the index into imagePrompts, carried on the
     card so the modal can find the original entry while a filter is active. */
  /* A real <button>, not a div+click: keyboard reachable, Enter/Space activate
     it for free, and it is exposed to assistive tech as an actionable control.
     Children are spans because <button> only admits phrasing content. The img
     is alt="" because the style name sits right beside it in the label. */
  grid.innerHTML = list.map((p, i) => `
    <button type="button" class="gallery-card reveal swatch-${p.i % 6} ${escapeHTML(p.size || "")}" style="animation-delay:${(i % 3) * 60}ms" data-id="${p.i}" aria-label="${escapeHTML(p.style)}, ${escapeHTML(p.cat)}. View prompt.">
      <span class="swatch-texture"></span>
      ${hasThumb(p.slug) ? `<img class="real-photo" src="images/${encodeURIComponent(p.slug)}.jpg" alt="" loading="lazy">` : ""}
      <span class="swatch-content">
        <span class="badge">${escapeHTML(p.cat)}</span>
        <span class="swatch-name">${escapeHTML(p.style)}</span>
      </span>
    </button>`).join("");

  grid.querySelectorAll(".gallery-card").forEach((card) => {
    card.addEventListener("click", () => openModal(Number(card.dataset.id)));
  });
  observeReveals();
}

/* The card that opened the dialog, so focus can go back to it on close. */
let modalReturnFocus = null;

function modalFocusables(){
  const modal = document.querySelector("#modalBackdrop .modal");
  if(!modal) return [];
  return [...modal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')]
    .filter((el) => !el.disabled && el.getClientRects().length);
}

/* Only bound while the dialog is open. Escape closes; Tab wraps at both ends so
   focus cannot escape into the page behind the overlay. */
function onModalKeydown(e){
  if(e.key === "Escape"){ e.preventDefault(); closeModal(); return; }
  if(e.key !== "Tab") return;

  const list = modalFocusables();
  if(!list.length) return;
  const first = list[0];
  const last = list[list.length - 1];

  if(e.shiftKey && document.activeElement === first){
    e.preventDefault();
    last.focus();
  } else if(!e.shiftKey && document.activeElement === last){
    e.preventDefault();
    first.focus();
  }
}

function openModal(id){
  const p = imagePrompts[id];
  const modalSwatch = document.getElementById("modalSwatch");
  modalSwatch.className = `modal-swatch swatch-${id % 6}`;
  /* alt="" — the name is in the heading and in .modal-swatch-name already. */
  const manifest = window.imageManifest;
  const hasThumb = !Array.isArray(manifest) || manifest.includes(p.slug);
  const thumb = hasThumb ? `<img class="real-photo" src="images/${encodeURIComponent(p.slug)}.jpg" alt="">` : "";
  modalSwatch.innerHTML = `<div class="swatch-texture"></div>${thumb}<span class="modal-swatch-name">${escapeHTML(p.style)}</span>`;
  document.getElementById("modalStyleName").textContent = p.style;
  document.getElementById("modalModel").textContent = p.cat;
  document.getElementById("modalPromptText").innerHTML = highlightVars(p.prompt);
  document.getElementById("modalCopyBtn").dataset.raw = p.prompt;

  const sendRow = document.getElementById("modalSendRow");
  if(sendRow){
    sendRow.innerHTML = sendRowHTML(p.prompt);
    bindSendButtons(sendRow);
  }

  modalReturnFocus = document.querySelector(`.gallery-card[data-id="${id}"]`) || document.activeElement;

  document.getElementById("modalBackdrop").classList.add("open");
  document.body.style.overflow = "hidden";
  document.addEventListener("keydown", onModalKeydown, true);
  /* Move focus into the dialog, or the trap has nothing to hold and a screen
     reader never learns the dialog opened. */
  document.getElementById("modalClose").focus();
}

function closeModal(){
  const backdrop = document.getElementById("modalBackdrop");
  if(!backdrop || !backdrop.classList.contains("open")) return;

  backdrop.classList.remove("open");
  document.body.style.overflow = "";
  document.removeEventListener("keydown", onModalKeydown, true);

  /* Back to the card that opened it — otherwise focus falls to <body> and a
     keyboard user restarts from the top of a 266-card grid. */
  if(modalReturnFocus && document.contains(modalReturnFocus)) modalReturnFocus.focus();
  modalReturnFocus = null;
}

/* ==================================================================
   TEXT PROMPT CATEGORY PAGE (ppt / essay / report / email)
   ================================================================== */
function initCategoryPage(){
  const list = document.getElementById("categoryPromptList");
  if(!list) return;

  /* prompts-text.js is a separate <script>; if it 404s or fails to parse the
     page would otherwise render an empty list with no explanation. */
  if(!textPromptsData){
    list.innerHTML = `
      <div class="gallery-error" role="alert">
        <p class="gallery-error-title">These prompts didn&rsquo;t load.</p>
        <p>prompts-text.js is missing or failed to parse. Try reloading &mdash; if it
        keeps happening, check that the file sits next to this page.</p>
      </div>`;
    return;
  }

  const category = list.dataset.category;
  const prompts = textPromptsData[category] || [];
  const visual = categoryVisuals[category] || categoryVisuals.essay;

  if(!prompts.length){
    list.innerHTML = `
      <div class="gallery-error" role="alert">
        <p class="gallery-error-title">No prompts in this category.</p>
        <p>prompts-text.js loaded but has nothing under <code>${escapeHTML(category)}</code>.</p>
      </div>`;
    return;
  }

  /* Reshuffled per visit; the filter and search then work over that order. */
  const ordered = shuffled(prompts);
  const state = { tag: "All", query: "" };

  const search = document.getElementById("categorySearch");
  const chipRow = document.getElementById("categoryChips");
  const countEl = document.getElementById("categoryCount");

  /* Chips are derived from the tags actually present, so adding a tag in
     prompts-text.js makes a new filter appear with no edit here. */
  if(chipRow){
    const tags = ["All", ...new Set(prompts.map((p) => p.tag).filter(Boolean))];
    chipRow.innerHTML = tags.map((t) =>
      `<button type="button" class="chip${t === "All" ? " active" : ""}" data-tag="${escapeHTML(t)}" aria-pressed="${t === "All"}">${escapeHTML(t)}</button>`
    ).join("");

    chipRow.querySelectorAll(".chip").forEach((chip) => {
      chip.addEventListener("click", () => {
        chipRow.querySelectorAll(".chip").forEach((c) => {
          c.classList.remove("active");
          c.setAttribute("aria-pressed", "false");
        });
        chip.classList.add("active");
        chip.setAttribute("aria-pressed", "true");
        state.tag = chip.dataset.tag;
        render();
      });
    });
  }

  if(search){
    search.placeholder = search.placeholder.replace(/\d+/, prompts.length);
    let timer;
    const apply = () => {
      const next = search.value.trim().toLowerCase();
      if(next === state.query) return;
      state.query = next;
      render();
    };
    search.addEventListener("input", () => {
      clearTimeout(timer);
      timer = setTimeout(apply, 120);
    });
    search.addEventListener("search", () => { clearTimeout(timer); apply(); });
    search.addEventListener("keydown", (e) => {
      if(e.key === "Enter"){ clearTimeout(timer); apply(); }
    });
  }

  function matching(){
    return ordered.filter((p) => {
      if(state.tag !== "All" && p.tag !== state.tag) return false;
      if(!state.query) return true;
      return (p.prompt + " " + (p.tag || "")).toLowerCase().includes(state.query);
    });
  }

  function render(){
    const items = matching();
    if(countEl) countEl.textContent = `${items.length} prompt${items.length === 1 ? "" : "s"}`;

    if(!items.length){
      list.innerHTML = `<p class="gallery-empty">No prompts match that search. Try a different word, or pick another filter.</p>`;
      return;
    }

    list.innerHTML = items.map((p, i) => `
    <div class="prompt-card reveal" style="animation-delay:${(i % 2) * 70}ms">
      <div class="prompt-thumb ${visual.swatch}">
        <div class="swatch-texture"></div>
        <span class="prompt-thumb-icon">${ICONS[visual.icon]}</span>
        <span class="prompt-thumb-label">${escapeHTML(p.tag || visual.label)}</span>
      </div>
      <div class="prompt-block-bar"><span class="demo-dot"></span><span>${escapeHTML(p.filename)}</span></div>
      <p class="prompt-text">${highlightVars(p.prompt)}</p>
      <div class="prompt-actions">
        <button type="button" class="btn btn-ghost btn-copy btn-sm" data-raw="${escapeHTML(p.prompt)}">${copyButtonHTML("Copy prompt")}</button>
        <div class="send-row">${sendRowHTML(p.prompt)}</div>
      </div>
    </div>
  `).join("");

    list.querySelectorAll(".btn-copy").forEach((btn) => {
      btn.addEventListener("click", function(){ copyText(this.dataset.raw, this); });
    });
    bindSendButtons(list);
    observeReveals();
  }

  render();
}

/* ==================================================================
   HERO DEMO CYCLE (index.html only, loops forever)
   ================================================================== */
async function runDemoCycle(){
  const textEl = document.getElementById("demoPromptText");
  if(!textEl) return;
  const resultEl = document.getElementById("demoResult");
  const filenameEl = document.getElementById("demoFilename");
  const badgeEl = document.getElementById("demoBadge");
  let demoIndex = 0;

  while(true){
    const pair = demoPairs[demoIndex % demoPairs.length];
    filenameEl.textContent = pair.filename;
    badgeEl.textContent = pair.model;
    textEl.textContent = "";
    resultEl.classList.remove("show");
    resultEl.innerHTML = "";

    if(prefersReducedMotion){
      textEl.textContent = pair.prompt;
    } else {
      for(let i = 0; i < pair.prompt.length; i++){
        textEl.textContent += pair.prompt[i];
        await sleep(26);
      }
    }
    await sleep(450);

    if(pair.type === "image"){
      /* The gradient swatch stands in for the render. This used to pull a photo
         from loremflickr.com, which put a third-party request on the homepage,
         broke the promise that the site works from disk with no network, and
         showed an unrelated stock photo rather than anything the prompt made. */
      resultEl.innerHTML = `<div class="demo-swatch swatch-${pair.hue}"><div class="swatch-texture"></div><span class="swatch-name">${escapeHTML(pair.style)}</span></div>`;
    } else {
      resultEl.innerHTML = `<pre class="demo-result-text">${escapeHTML(pair.result)}</pre>`;
    }
    requestAnimationFrame(() => resultEl.classList.add("show"));

    await sleep(prefersReducedMotion ? 900 : 3400);
    resultEl.classList.remove("show");
    await sleep(450);
    demoIndex++;
  }
}

/* See builder-data.js — only builder.html loads it. */
const builderOptions = window.builderOptions || null;
const builderRatios = Array.isArray(window.builderRatios) ? window.builderRatios : [];

/* ==================================================================
   PROMPT BUILDER (builder.html only)
   ================================================================== */
function initBuilder(){
  const form = document.getElementById("builderForm");
  if(!form) return;

  /* builder-data.js supplies every dropdown. Without it the selects would sit
     there empty and the page would look broken for no stated reason. */
  if(!builderOptions){
    const panel = document.querySelector(".builder-output-panel") || form;
    panel.insertAdjacentHTML("afterbegin", `
      <div class="gallery-error" role="alert">
        <p class="gallery-error-title">The builder didn&rsquo;t load.</p>
        <p>builder-data.js is missing or failed to parse, so there are no options
        to choose from. Try reloading.</p>
      </div>`);
    return;
  }

  const fields = ["style","lighting","composition","mood","palette","finish"];

  fields.forEach((field) => {
    const select = document.getElementById(`builder-${field}`);
    select.innerHTML = `<option value="">— none —</option>` +
      builderOptions[field].map((opt) => `<option value="${escapeHTML(opt)}">${escapeHTML(opt)}</option>`).join("");
  });

  const ratioSelect = document.getElementById("builder-ratio");
  ratioSelect.innerHTML = builderRatios.map((r) => `<option value="${escapeHTML(r)}">${escapeHTML(r)}</option>`).join("");

  form.addEventListener("input", buildPrompt);
  form.addEventListener("change", buildPrompt);

  /* Real <form> so Reset can use native reset(), but there is nothing to submit
     to — swallow Enter rather than letting it reload the page. */
  form.addEventListener("submit", (e) => e.preventDefault());

  document.getElementById("builderRandomBtn").addEventListener("click", () => {
    fields.forEach((field) => {
      const opts = builderOptions[field];
      document.getElementById(`builder-${field}`).value = opts[Math.floor(Math.random() * opts.length)];
    });
    buildPrompt();
  });

  /* Native reset() restores every control to its first/blank option, which for
     the six style selects is the "— none —" entry rendered above. */
  document.getElementById("builderResetBtn").addEventListener("click", () => {
    form.reset();
    buildPrompt();
  });

  const copyBtn = document.getElementById("builderCopyBtn");
  copyBtn.innerHTML = copyButtonHTML("Copy prompt");
  copyBtn.addEventListener("click", function(){
    const text = document.getElementById("builderOutput").dataset.raw || "";
    if(text) copyText(text, this);
  });

  buildPrompt();
}

/* Assembles the prompt from whatever is filled in. Empty fields are skipped,
   so a subject alone still produces something valid. */
function buildPrompt(){
  const val = (id) => (document.getElementById(id).value || "").trim();

  const subject = val("builder-subject");
  const model = val("builder-model");
  const ratio = val("builder-ratio");
  const extra = val("builder-extra");

  const parts = [
    subject,
    val("builder-style"),
    val("builder-lighting"),
    val("builder-composition"),
    val("builder-mood"),
    val("builder-palette"),
    val("builder-finish"),
    extra
  ].filter(Boolean);

  let prompt = parts.join(", ");

  if(prompt && ratio){
    if(model === "Midjourney") prompt += ` --ar ${ratio} --v 6`;
    else if(model === "Stable Diffusion" && ratio !== "1:1") prompt += `, aspect ratio ${ratio}`;
    else if(ratio !== "1:1") prompt += `, ${ratio} aspect ratio`;
  }

  const output = document.getElementById("builderOutput");
  const counter = document.getElementById("builderCount");

  if(!prompt){
    output.innerHTML = `<span class="builder-placeholder">Describe your subject above to start building…</span>`;
    output.dataset.raw = "";
    counter.textContent = "0 words";
  } else {
    output.textContent = prompt;
    output.dataset.raw = prompt;
    const words = prompt.split(/\s+/).length;
    counter.textContent = `${words} word${words === 1 ? "" : "s"}`;
  }
}


/* ==================================================================
   INIT — runs on every page; each function no-ops if its elements aren't present
   ================================================================== */
setActiveNav();
initNavIndicator();
initNavScrollState();
initThemeToggle();
initMobileNav();
initPageTransitions();
initGallery();
initCountUp();
initCategoryPage();
initBuilder();
observeReveals();
runDemoCycle();
