/* ==================================================================
   DATA

   IMAGE PROMPTS now live in prompts-image.js (266 image-to-image transformation
   prompts, generated by build_prompts.py). That file sets window.imagePrompts
   and must be loaded before this one. To add or edit image prompts, edit
   build_prompts.py and re-run it — don't edit prompts-image.js by hand.
   ================================================================== */
const imagePrompts = Array.isArray(window.imagePrompts) ? window.imagePrompts : [];

/* To add a new TEXT prompt: push {filename, prompt} into the matching array.
   [bracketed] words are auto-highlighted as fill-in variables — keep placeholders
   in that format. Each key (ppt/essay/report/email) feeds its own page:
   the page's #categoryPromptList element has a matching data-category attribute. */
const textPromptsData = {
  ppt: [
    { filename:"ppt_01.txt", prompt:"Create a [number]-slide presentation outline on [topic] for a [audience type] audience. Include a title slide, an agenda, [number] content slides with 3 bullet points each, and a closing summary slide. Keep language [tone]." },
    { filename:"ppt_02.txt", prompt:"Turn the following notes into slide-ready bullet points, max 5 words per line, grouped under clear section headers: [paste notes]" },
    { filename:"ppt_03.txt", prompt:"Suggest a slide-by-slide structure for a [duration]-minute pitch deck for [product or idea], following a problem → solution → market → ask format." },
    { filename:"ppt_04.txt", prompt:"Write speaker notes for a slide titled '[slide title]', assuming the audience already knows [background context]. Keep it under 100 words, conversational tone." }
  ],
  essay: [
    { filename:"essay_01.txt", prompt:"Write a [word count]-word essay on [topic] in a [tone] tone. Structure it with an introduction that states a clear thesis, [number] body paragraphs each covering one supporting point, and a conclusion that restates the thesis without repeating it word-for-word." },
    { filename:"essay_02.txt", prompt:"Give me 5 possible thesis statements for an essay about [topic], each taking a slightly different angle." },
    { filename:"essay_03.txt", prompt:"Rewrite this paragraph to sound more [tone] while keeping the same meaning: [paste paragraph]" },
    { filename:"essay_04.txt", prompt:"Write a counter-argument paragraph for an essay arguing that [position], addressing the strongest opposing view and rebutting it in [word count] words." }
  ],
  report: [
    { filename:"report_01.txt", prompt:"Write a [report type] report on [topic] for [audience], structured as: Executive Summary, Background, Findings ([number] key points), Recommendations, Conclusion. Total length: [word count] words." },
    { filename:"report_02.txt", prompt:"Summarize the following data into a concise 'Key Findings' section with [number] bullet points, each starting with the most important number or result: [paste data]" },
    { filename:"report_03.txt", prompt:"Draft an executive summary for a report about [topic], written for [audience] who won't read the full report — under 200 words." },
    { filename:"report_04.txt", prompt:"Convert this list of raw observations into a formal 'Recommendations' section, phrased as clear action items: [paste observations]" }
  ],
  email: [
    { filename:"email_01.txt", prompt:"Write a [tone] email to [recipient] about [topic]. Keep it under [word count] words, include a clear subject line, and end with a specific call to action." },
    { filename:"email_02.txt", prompt:"Draft a follow-up email to [recipient] after [event or meeting], referencing [specific detail] and proposing [next step]." },
    { filename:"email_03.txt", prompt:"Write a polite decline email to [recipient] regarding [request], keeping the door open for future collaboration." },
    { filename:"email_04.txt", prompt:"Turn these rough notes into a professional email to [recipient]: [paste notes]. Tone: [tone]." }
  ]
};

/* Hero demo (index.html only) — cycles automatically, mixing image and text
   results so the hero shows both halves of the site. */
const demoPairs = [
  { type:"image", filename:"image_04.txt", model:"Midjourney", style:"Neon Noir", hue:4, keywords:"cyberpunk,alley,neon",
    prompt:"cyberpunk alley, neon rain reflections, cinematic wide shot, teal and magenta lighting --ar 16:9 --v 6" },
  { type:"text", filename:"email_02.txt", model:"Claude",
    prompt:"Write a confident cold email to a hiring manager about a Frontend role, under 120 words, no generic flattery.",
    result:"Subject: A tool I built that might help your onboarding flow\n\nHi Priya — I recently cut my team's deploy time in half with a small internal tool. I think something similar could streamline onboarding for new engineers on your team. Worth a quick 15-minute call this week?" },
  { type:"image", filename:"image_11.txt", model:"Midjourney", style:"Watercolor Whimsy", hue:0, keywords:"forest,mist,dawn",
    prompt:"misty pine forest at dawn, volumetric light rays through fog, muted teal and amber palette --ar 16:9" },
  { type:"text", filename:"ppt_03.txt", model:"GPT",
    prompt:"Give me a 3-slide pitch outline for a campus food delivery startup: problem, solution, ask.",
    result:"1. Problem — students skip meals during exam week; existing delivery apps are too slow for campus routes.\n2. Solution — a 10-minute delivery network run by students, for students.\n3. Ask — seed funding to launch on 3 campuses this semester." }
];

/* ==================================================================
   ICONS — inline SVG strings, reused wherever needed. No emoji on this site.
   ================================================================== */
const ICONS = {
  copy:  '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>',
  check: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12l5 5L19 8"/></svg>',
  close: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M6 6l12 12M18 6L6 18"/></svg>',
  arrow: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M7 17L17 7M9 7h8v8"/></svg>',
  spark: '<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9L12 3z"/></svg>',
  ppt:    '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="12" rx="1.5"/><path d="M8 21h8M12 17v4"/></svg>',
  essay:  '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2h9l5 5v15a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z"/><path d="M14 2v5h5M8 13h8M8 17h5"/></svg>',
  report: '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 16v-3M12 16V8M16 16v-6"/></svg>',
  email:  '<svg class="icon-lg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></svg>'
};

/* Thumbnail treatment per text category — gradient + icon, so every prompt card
   has a visual anchor the same way the image cards do. */
const categoryVisuals = {
  ppt:    { icon:"ppt",    swatch:"swatch-1", label:"Presentation" },
  essay:  { icon:"essay",  swatch:"swatch-3", label:"Essay" },
  report: { icon:"report", swatch:"swatch-2", label:"Report" },
  email:  { icon:"email",  swatch:"swatch-0", label:"Email" }
};

/* ==================================================================
   HELPERS
   ================================================================== */
const prefersReducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function highlightVars(str){
  return str.replace(/\[([^\]]+)\]/g, '<span class="var">[$1]</span>');
}
function escapeAttr(str){
  return str.replace(/&/g,"&amp;").replace(/"/g,"&quot;");
}
function copyButtonHTML(label){
  return `${ICONS.copy}<span>${label}</span>`;
}
function slugify(str){
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
/* Tries a local image first (images/<slug>.jpg — see /images/README.md), falls back
   to a keyword-matched stock photo if that's missing, then to the plain gradient
   swatch if that fails too. Never leaves a broken-image icon. */
function onImgError(img){
  if(img.dataset.fallback){
    img.src = img.dataset.fallback;
    img.removeAttribute("data-fallback");
  } else {
    img.remove();
  }
}

let revealObserver;
function observeReveals(){
  if(!revealObserver){
    revealObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if(entry.isIntersecting){
          entry.target.classList.add("in-view");
          revealObserver.unobserve(entry.target);
        }
      });
    }, { threshold:0.15 });
  }
  document.querySelectorAll(".reveal:not(.in-view)").forEach((el) => revealObserver.observe(el));
}

/* Screen-reader announcements. One shared polite live region, created lazily so
   pages that never announce anything don't carry the node. */
let liveRegion;
function announce(message){
  if(!liveRegion){
    liveRegion = document.createElement("div");
    liveRegion.className = "sr-only";
    liveRegion.setAttribute("role", "status");
    liveRegion.setAttribute("aria-live", "polite");
    document.body.appendChild(liveRegion);
  }
  /* Clear first, or repeating the same string is not re-announced. */
  liveRegion.textContent = "";
  setTimeout(() => { liveRegion.textContent = message; }, 60);
}

/* Pre-async-clipboard fallback. navigator.clipboard is undefined on every
   non-secure origin, which includes opening these pages straight off the
   filesystem — a supported way to use this site — so this path is not exotic. */
function legacyCopy(text){
  const ta = document.createElement("textarea");
  ta.value = text;
  ta.setAttribute("readonly", "");
  /* Off-screen, not display:none — execCommand needs a real selection. */
  ta.style.cssText = "position:fixed;top:0;left:-9999px;opacity:0;";
  document.body.appendChild(ta);

  let ok = false;
  try {
    ta.select();
    ta.setSelectionRange(0, ta.value.length);
    ok = document.execCommand("copy");
  } catch(err){
    ok = false;
  }
  ta.remove();
  return ok;
}

function flashCopyResult(btn, ok){
  if(btn.dataset.copyBusy) return;
  btn.dataset.copyBusy = "1";

  const original = btn.innerHTML;
  btn.innerHTML = ok
    ? `${ICONS.check}<span>Copied!</span>`
    : `${ICONS.close}<span>Copy failed</span>`;
  btn.classList.add(ok ? "copied" : "copy-failed");
  announce(ok ? "Prompt copied to clipboard" : "Copy failed — select the prompt text and copy it manually");

  setTimeout(() => {
    btn.innerHTML = original;
    btn.classList.remove("copied", "copy-failed");
    delete btn.dataset.copyBusy;
  }, ok ? 1600 : 2800);
}

/* Async clipboard where it exists, textarea fallback where it doesn't, and a
   visible failure state if both are refused — previously a rejected promise or
   a missing API produced no feedback at all. */
function copyText(text, btn){
  if(navigator.clipboard && window.isSecureContext){
    navigator.clipboard.writeText(text).then(
      () => flashCopyResult(btn, true),
      () => flashCopyResult(btn, legacyCopy(text))
    );
    return;
  }
  flashCopyResult(btn, legacyCopy(text));
}

/* ==================================================================
   NAV — active link, mobile toggle (runs on every page)
   ================================================================== */
function setActiveNav(){
  let file = location.pathname.split("/").pop();
  if(file === "") file = "index.html";
  const textGroup = ["text.html","ppt.html","essay.html","report.html","email.html"];
  document.querySelectorAll(".nav-link").forEach((link) => {
    const target = link.dataset.page;
    const isActive = target === file || (target === "text.html" && textGroup.includes(file));
    link.classList.toggle("active", isActive);
  });
}

function initMobileNav(){
  const navToggle = document.getElementById("navToggle");
  const navLinksEl = document.getElementById("navLinks");
  if(!navToggle || !navLinksEl) return;
  navToggle.addEventListener("click", () => {
    const isOpen = navLinksEl.classList.toggle("open");
    navToggle.classList.toggle("open", isOpen);
    navToggle.setAttribute("aria-expanded", String(isOpen));
  });
}

/* ==================================================================
   PAGE TRANSITIONS — fade in on load, fade out before internal navigation
   ================================================================== */
function initPageTransitions(){
  requestAnimationFrame(() => requestAnimationFrame(() => document.body.classList.add("loaded")));

  document.addEventListener("click", (e) => {
    /* Anything that is not a plain left-click belongs to the browser: modifier
       clicks open new tabs or windows, and middle-click arrives as auxclick. */
    if(e.defaultPrevented || e.button !== 0) return;
    if(e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;

    const link = e.target.closest("a");
    if(!link || link.target === "_blank" || link.hasAttribute("download")) return;

    const href = link.getAttribute("href");
    if(!href || href.startsWith("#")) return;

    /* Only relative in-site navigations get the fade. Any href carrying an
       explicit scheme — http:, mailto:, tel:, data:, blob: — is left alone.
       data: matters: browsers refuse top-level data: navigation, so routing the
       builder's Download link through window.location silently did nothing. */
    if(href.startsWith("//") || /^[a-z][a-z0-9+.-]*:/i.test(href)) return;

    e.preventDefault();
    document.body.classList.remove("loaded");
    document.body.classList.add("leaving");
    setTimeout(() => { window.location.href = href; }, prefersReducedMotion ? 0 : 260);
  });
}

/* ==================================================================
   IMAGE GALLERY + MODAL (images.html only)
   ================================================================== */
let galleryState = { cat: "All", query: "" };

/* prompts-image.js is a separate <script>; if it 404s, is blocked, or fails to
   parse, we arrive here with nothing. Say that plainly — an empty grid plus
   "no prompts match that search" blames the visitor for a load failure. */
function renderGalleryUnavailable(){
  const grid = document.getElementById("galleryGrid");
  const countEl = document.getElementById("galleryCount");
  const chipRow = document.getElementById("galleryChips");
  const search = document.getElementById("gallerySearch");

  if(countEl) countEl.textContent = "unavailable";
  if(chipRow) chipRow.innerHTML = "";
  if(search){
    search.disabled = true;
    search.placeholder = "Search unavailable";
  }

  grid.innerHTML = `
    <div class="gallery-error" role="alert">
      <p class="gallery-error-title">The prompt library didn&rsquo;t load.</p>
      <p>prompts-image.js is missing or failed to parse, so there is nothing to show.
      Try reloading. If it keeps happening, regenerate it with
      <code>python3 build_prompts.py</code>.</p>
    </div>`;
}

function initGallery(){
  const grid = document.getElementById("galleryGrid");
  if(!grid) return;

  if(!imagePrompts.length){
    renderGalleryUnavailable();
    return;
  }

  /* Category chips are derived from the data, so adding a new category in
     build_prompts.py makes a new filter appear with no edit here. */
  const cats = ["All", ...new Set(imagePrompts.map((p) => p.cat))];
  const chipRow = document.getElementById("galleryChips");
  chipRow.innerHTML = cats.map((c) =>
    `<button class="chip${c === "All" ? " active" : ""}" data-cat="${escapeAttr(c)}">${c}</button>`
  ).join("");

  chipRow.querySelectorAll(".chip").forEach((chip) => {
    chip.addEventListener("click", () => {
      chipRow.querySelectorAll(".chip").forEach((c) => c.classList.remove("active"));
      chip.classList.add("active");
      galleryState.cat = chip.dataset.cat;
      renderGallery();
    });
  });

  const search = document.getElementById("gallerySearch");
  search.addEventListener("input", () => {
    galleryState.query = search.value.trim().toLowerCase();
    renderGallery();
  });

  const modalCloseBtn = document.getElementById("modalClose");
  const modalBackdrop = document.getElementById("modalBackdrop");
  const modalCopyBtn = document.getElementById("modalCopyBtn");
  modalCloseBtn.innerHTML = ICONS.close;
  modalCopyBtn.innerHTML = copyButtonHTML("Copy prompt");

  modalCloseBtn.addEventListener("click", closeModal);
  modalBackdrop.addEventListener("click", (e) => { if(e.target === modalBackdrop) closeModal(); });
  document.addEventListener("keydown", (e) => { if(e.key === "Escape") closeModal(); });
  modalCopyBtn.addEventListener("click", function(){ copyText(this.dataset.raw, this); });

  renderGallery();
}

function filteredPrompts(){
  return imagePrompts.filter((p) => {
    if(galleryState.cat !== "All" && p.cat !== galleryState.cat) return false;
    if(!galleryState.query) return true;
    return (p.style + " " + p.cat + " " + p.prompt).toLowerCase().includes(galleryState.query);
  });
}

function renderGallery(){
  const grid = document.getElementById("galleryGrid");
  const countEl = document.getElementById("galleryCount");
  const list = filteredPrompts();

  countEl.textContent = `${list.length} prompt${list.length === 1 ? "" : "s"}`;

  if(!list.length){
    grid.innerHTML = `<p class="gallery-empty">No prompts match that search. Try a different word, or pick another category.</p>`;
    return;
  }

  /* Index into imagePrompts is stored on the card so the modal can find the
     original entry even while a filter is active. */
  grid.innerHTML = list.map((p, i) => {
    const realIndex = imagePrompts.indexOf(p);
    return `
    <div class="gallery-card reveal swatch-${realIndex % 6} ${p.size || ""}" style="transition-delay:${(i % 3) * 60}ms" data-id="${realIndex}">
      <div class="swatch-texture"></div>
      <img class="real-photo" src="images/${p.slug}.jpg" alt="${escapeAttr(p.style)} example" loading="lazy" onerror="this.remove()">
      <div class="swatch-content">
        <span class="badge">${p.cat}</span>
        <span class="swatch-name">${p.style}</span>
      </div>
    </div>`;
  }).join("");

  grid.querySelectorAll(".gallery-card").forEach((card) => {
    card.addEventListener("click", () => openModal(Number(card.dataset.id)));
  });
  observeReveals();
}

function openModal(id){
  const p = imagePrompts[id];
  const modalSwatch = document.getElementById("modalSwatch");
  modalSwatch.className = `modal-swatch swatch-${id % 6}`;
  modalSwatch.innerHTML = `<div class="swatch-texture"></div><img class="real-photo" src="images/${p.slug}.jpg" alt="${escapeAttr(p.style)} example" onerror="this.remove()"><span class="modal-swatch-name">${p.style}</span>`;
  document.getElementById("modalStyleName").textContent = p.style;
  document.getElementById("modalModel").textContent = p.cat;
  document.getElementById("modalPromptText").innerHTML = highlightVars(p.prompt);
  document.getElementById("modalCopyBtn").dataset.raw = p.prompt;
  document.getElementById("modalBackdrop").classList.add("open");
  document.body.style.overflow = "hidden";
}

function closeModal(){
  const backdrop = document.getElementById("modalBackdrop");
  if(!backdrop) return;
  backdrop.classList.remove("open");
  document.body.style.overflow = "";
}

/* ==================================================================
   TEXT PROMPT CATEGORY PAGE (ppt / essay / report / email)
   ================================================================== */
function initCategoryPage(){
  const list = document.getElementById("categoryPromptList");
  if(!list) return;
  const category = list.dataset.category;
  const prompts = textPromptsData[category] || [];

  const visual = categoryVisuals[category] || categoryVisuals.essay;

  list.innerHTML = prompts.map((p, i) => `
    <div class="prompt-card reveal" style="transition-delay:${(i % 2) * 70}ms">
      <div class="prompt-thumb ${visual.swatch}">
        <div class="swatch-texture"></div>
        <span class="prompt-thumb-icon">${ICONS[visual.icon]}</span>
        <span class="prompt-thumb-label">${visual.label}</span>
      </div>
      <div class="prompt-block-bar"><span class="demo-dot"></span><span>${p.filename}</span></div>
      <p class="prompt-text">${highlightVars(p.prompt)}</p>
      <button class="btn btn-ghost btn-copy btn-sm" data-raw="${escapeAttr(p.prompt)}">${copyButtonHTML("Copy prompt")}</button>
    </div>
  `).join("");

  list.querySelectorAll(".btn-copy").forEach((btn) => {
    btn.addEventListener("click", function(){ copyText(this.dataset.raw, this); });
  });
  observeReveals();
}

/* ==================================================================
   HERO DEMO CYCLE (index.html only, loops forever)
   ================================================================== */
async function runDemoCycle(){
  const textEl = document.getElementById("demoPromptText");
  if(!textEl) return;
  const resultEl = document.getElementById("demoResult");
  const filenameEl = document.getElementById("demoFilename");
  const badgeEl = document.getElementById("demoBadge");
  let demoIndex = 0;

  while(true){
    const pair = demoPairs[demoIndex % demoPairs.length];
    filenameEl.textContent = pair.filename;
    badgeEl.textContent = pair.model;
    textEl.textContent = "";
    resultEl.classList.remove("show");
    resultEl.innerHTML = "";

    if(prefersReducedMotion){
      textEl.textContent = pair.prompt;
    } else {
      for(let i = 0; i < pair.prompt.length; i++){
        textEl.textContent += pair.prompt[i];
        await sleep(26);
      }
    }
    await sleep(450);

    if(pair.type === "image"){
      resultEl.innerHTML = `<div class="demo-swatch swatch-${pair.hue}"><div class="swatch-texture"></div><img class="real-photo" src="https://loremflickr.com/560/320/${pair.keywords}" alt="Generated result" onerror="this.remove()"><span class="swatch-name">${pair.style}</span></div>`;
    } else {
      resultEl.innerHTML = `<pre class="demo-result-text">${pair.result}</pre>`;
    }
    requestAnimationFrame(() => resultEl.classList.add("show"));

    await sleep(prefersReducedMotion ? 900 : 3400);
    resultEl.classList.remove("show");
    await sleep(450);
    demoIndex++;
  }
}

/* ==================================================================
   PROMPT BUILDER DATA (builder.html)
   Pure templates — no API key, no network call. To add an option, just add a
   string to the relevant array; it appears in the dropdown automatically.
   Each entry is the literal phrase injected into the assembled prompt.
   ================================================================== */
const builderOptions = {
  style: [
    "lush hand-painted watercolor style, soft bleeding edges, textured paper grain",
    "charcoal drawing, monochromatic smoky gradients, heavy shading",
    "traditional woodblock print, strong black outlines, flat color zones",
    "ink wash painting, fluid brushstrokes, varying opacity, negative space",
    "colored pencil sketch, visible textured linework, soft shading",
    "gouache painting, heavy opaque matte color, deep saturated tones",
    "oil painting with thick impasto brushstrokes, visible 3D relief",
    "linocut print, bold blocky negative space, raw chiseled edges",
    "stained glass, bold black leading, glowing translucent panes",
    "layered papercraft and origami, flat folded-paper shapes, 3D depth",
    "claymation stop-motion, molded clay texture, visible fingerprints",
    "embroidery, characters woven from visible threads and fabric texture",
    "fresco mural, cracked plaster texture, faded historical pigment",
    "1980s VHS home-video look, muted tones, chromatic aberration, scanlines",
    "city pop album-cover aesthetic, sleek 80s urban nightscape, neon reflections",
    "lo-fi aesthetic, high grain, low contrast, drifting dust particles",
    "Technicolor glow, oversaturated primaries, blooming halo around lights",
    "sepia-toned vintage photography, monochromatic brown tones",
    "8-bit pixel art, retro video game squares, limited palette",
    "16-bit JRPG pixel sprites, vibrant parallax background",
    "risograph print, misaligned two-color layers, visible grain",
    "art deco poster, bold geometric linework, metallic gold and teal",
    "art nouveau, whiplash curves, elegant floral framing",
    "low-poly 3D render, faceted geometric surfaces, flat shading",
    "vector illustration, ultra-clean geometric lines, flat color",
    "glitch art and datamoshing, corrupted artifacts, color-channel bleed",
    "psychedelic swirling neon palette, melting tie-dye distortion",
    "fisheye lens distortion, ultra-wide bulbous perspective",
    "heat-haze mirage, shimmering warping distortion",
    "steampunk, cluttered brass gears and rusted mechanical detail",
    "dieselpunk, dark oily heavy machinery under a grey sky",
    "cottagecore, cozy overgrown cabin, wildflowers, warm domestic detail",
    "dark fantasy, moody shadowy forest, pale spirits, gothic undertones",
    "cosmic horror, soft pastel depiction of colossal indifferent entities",
    "post-apocalyptic ruins reclaimed by vibrant green moss and trees",
    "biomechanical fusion of living tissue and vintage machinery",
    "chibi super-deformed proportions, oversized head, simple dot eyes",
    "liminal space, empty and unsettlingly quiet, flat even lighting"
  ],
  lighting: [
    "golden hour lighting, long warm shadows, amber light leaks",
    "blue hour, cool dusk tones, soft ambient glow",
    "overcast diffused light, shadowless and even",
    "dramatic god rays piercing heavy clouds",
    "bioluminescent glow, deep blues and indigos",
    "neon noir, blinding commercial neon against wet dark pavement",
    "harsh direct midday sun, hard-edged shadows",
    "soft studio lighting, single gentle shadow",
    "rim lighting, subject outlined against a dark background",
    "candlelight, warm flickering pools of light",
    "moonlight, cool silver highlights, deep shadow",
    "backlit silhouette, subject dark against bright haze"
  ],
  composition: [
    "cinematic wide shot",
    "extreme close-up",
    "overhead flat lay",
    "low angle looking up",
    "high angle looking down",
    "symmetrical centered composition",
    "rule-of-thirds off-center framing",
    "shallow depth of field, blurred background",
    "wide establishing landscape shot",
    "tight portrait crop",
    "over-the-shoulder view",
    "macro detail shot"
  ],
  mood: [
    "nostalgic and warm",
    "quiet and melancholy",
    "tense and ominous",
    "peaceful and serene",
    "energetic and chaotic",
    "dreamlike and surreal",
    "gritty and somber",
    "whimsical and playful",
    "epic and awe-inspiring",
    "lonely and isolated",
    "cozy and intimate",
    "cold and clinical"
  ],
  palette: [
    "muted earth tones",
    "vibrant jewel tones",
    "monochrome black and white",
    "teal and orange contrast",
    "soft pastel palette",
    "high-contrast primary colors",
    "desaturated washed-out tones",
    "warm amber and gold",
    "cool blues and greys",
    "neon magenta and cyan"
  ],
  finish: [
    "highly detailed, ultra sharp",
    "soft focus, gentle blur",
    "heavy film grain",
    "clean and minimal, lots of negative space",
    "richly textured surfaces",
    "glossy and reflective",
    "matte and flat",
    "painterly and loose"
  ]
};

/* Aspect ratios — the flag syntax differs per model, handled in buildPrompt(). */
const builderRatios = ["1:1", "16:9", "9:16", "4:5", "3:2", "2:3"];

/* ==================================================================
   PROMPT BUILDER (builder.html only)
   ================================================================== */
function initBuilder(){
  const form = document.getElementById("builderForm");
  if(!form) return;

  const fields = ["style","lighting","composition","mood","palette","finish"];

  fields.forEach((field) => {
    const select = document.getElementById(`builder-${field}`);
    select.innerHTML = `<option value="">— none —</option>` +
      builderOptions[field].map((opt) => `<option value="${escapeAttr(opt)}">${opt}</option>`).join("");
  });

  const ratioSelect = document.getElementById("builder-ratio");
  ratioSelect.innerHTML = builderRatios.map((r) => `<option value="${r}">${r}</option>`).join("");

  form.addEventListener("input", buildPrompt);
  form.addEventListener("change", buildPrompt);

  /* Real <form> so Reset can use native reset(), but there is nothing to submit
     to — swallow Enter rather than letting it reload the page. */
  form.addEventListener("submit", (e) => e.preventDefault());

  document.getElementById("builderRandomBtn").addEventListener("click", () => {
    fields.forEach((field) => {
      const opts = builderOptions[field];
      document.getElementById(`builder-${field}`).value = opts[Math.floor(Math.random() * opts.length)];
    });
    buildPrompt();
  });

  /* Native reset() restores every control to its first/blank option, which for
     the six style selects is the "— none —" entry rendered above. */
  document.getElementById("builderResetBtn").addEventListener("click", () => {
    form.reset();
    buildPrompt();
  });

  const copyBtn = document.getElementById("builderCopyBtn");
  copyBtn.innerHTML = copyButtonHTML("Copy prompt");
  copyBtn.addEventListener("click", function(){
    const text = document.getElementById("builderOutput").dataset.raw || "";
    if(text) copyText(text, this);
  });

  buildPrompt();
}

/* Assembles the prompt from whatever is filled in. Empty fields are skipped,
   so a subject alone still produces something valid. */
function buildPrompt(){
  const val = (id) => (document.getElementById(id).value || "").trim();

  const subject = val("builder-subject");
  const model = val("builder-model");
  const ratio = val("builder-ratio");
  const extra = val("builder-extra");

  const parts = [
    subject,
    val("builder-style"),
    val("builder-lighting"),
    val("builder-composition"),
    val("builder-mood"),
    val("builder-palette"),
    val("builder-finish"),
    extra
  ].filter(Boolean);

  let prompt = parts.join(", ");

  if(prompt && ratio){
    if(model === "Midjourney") prompt += ` --ar ${ratio} --v 6`;
    else if(model === "Stable Diffusion" && ratio !== "1:1") prompt += `, aspect ratio ${ratio}`;
    else if(ratio !== "1:1") prompt += `, ${ratio} aspect ratio`;
  }

  const output = document.getElementById("builderOutput");
  const counter = document.getElementById("builderCount");

  if(!prompt){
    output.innerHTML = `<span class="builder-placeholder">Describe your subject above to start building…</span>`;
    output.dataset.raw = "";
    counter.textContent = "0 words";
  } else {
    output.textContent = prompt;
    output.dataset.raw = prompt;
    const words = prompt.split(/\s+/).length;
    counter.textContent = `${words} word${words === 1 ? "" : "s"}`;
  }
}

/* ==================================================================
   OPTIONAL LIVE GENERATION (builder.html)

   The key is typed into the page at runtime and held in memory for this tab
   only — it is never written into any file and never saved to disk, so nothing
   secret ships with the site. Closing the tab clears it.

   DO NOT hardcode your key anywhere in script.js or the HTML. Anything in those
   files is downloaded by every visitor and readable via View Source. For bulk
   generation of the gallery images, use generate-images.js instead — that runs
   on your machine with the key in an environment variable.
   ================================================================== */
const GEMINI_MODEL = "gemini-3.1-flash-image";
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

async function generateWithGemini(prompt, apiKey){
  const res = await fetch(GEMINI_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
    body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
  });

  if(!res.ok){
    let detail = `HTTP ${res.status}`;
    try {
      const err = await res.json();
      if(err?.error?.message) detail = err.error.message;
    } catch(e){ /* keep the status-code fallback */ }
    throw new Error(detail);
  }

  const data = await res.json();
  const parts = data?.candidates?.[0]?.content?.parts || [];
  const imagePart = parts.find((p) => p.inlineData?.data);

  if(!imagePart){
    const textPart = parts.find((p) => p.text);
    throw new Error(textPart ? `No image returned — model said: ${textPart.text.slice(0, 160)}` : "No image in response");
  }
  return `data:${imagePart.inlineData.mimeType || "image/png"};base64,${imagePart.inlineData.data}`;
}

function initBuilderGenerate(){
  const genBtn = document.getElementById("builderGenBtn");
  if(!genBtn) return;

  const keyInput = document.getElementById("builderApiKey");
  const statusEl = document.getElementById("builderGenStatus");
  const previewEl = document.getElementById("builderPreview");

  genBtn.innerHTML = `${ICONS.spark}<span>Generate preview</span>`;

  genBtn.addEventListener("click", async () => {
    const prompt = document.getElementById("builderOutput").dataset.raw || "";
    const apiKey = keyInput.value.trim();

    if(!prompt){
      statusEl.textContent = "Build a prompt first — start with a subject.";
      statusEl.className = "builder-gen-status is-warn";
      return;
    }
    if(!apiKey){
      statusEl.textContent = "Paste your Gemini API key above to generate.";
      statusEl.className = "builder-gen-status is-warn";
      keyInput.focus();
      return;
    }

    genBtn.disabled = true;
    statusEl.textContent = "Generating…";
    statusEl.className = "builder-gen-status is-busy";
    previewEl.innerHTML = "";

    try {
      const dataUrl = await generateWithGemini(prompt, apiKey);
      previewEl.innerHTML = `<img src="${dataUrl}" alt="Generated preview">
        <a class="btn btn-ghost btn-sm builder-download" href="${dataUrl}" download="promptlib-preview.jpg">Download</a>`;
      statusEl.textContent = "Done.";
      statusEl.className = "builder-gen-status is-ok";
    } catch (err) {
      statusEl.textContent = `Failed — ${err.message}`;
      statusEl.className = "builder-gen-status is-err";
    } finally {
      genBtn.disabled = false;
    }
  });
}

/* ==================================================================
   INIT — runs on every page; each function no-ops if its elements aren't present
   ================================================================== */
setActiveNav();
initMobileNav();
initPageTransitions();
initGallery();
initCategoryPage();
initBuilder();
initBuilderGenerate();
observeReveals();
runDemoCycle();
