/* ==================================================================
   manifest.js — GENERATED, do not edit by hand.

   Slugs of the thumbnails present in this folder. images.html reads this
   so it only requests thumbnails that exist instead of 404ing on all 266.

   Regenerate after adding or removing files here:
       node build-manifest.js
   ================================================================== */
window.imageManifest = [
  "16-bit-sprite",
  "4k-ultra-sharp",
  "8k-hyper-detail",
  "90s-anime",
  "acrylic-painting",
  "airbrush-art",
  "brush-pen-illustration",
  "caricature",
  "cel-shaded-3d",
  "chalkboard-drawing",
  "character-sheet",
  "charcoal-drawing",
  "chibi-style",
  "children-s-picture-book",
  "classic-2d-feature-animation",
  "claymation-frame",
  "colored-pencil",
  "coloring-book-page",
  "comic-book-panel",
  "concept-art",
  "conte-crayon",
  "crayon-drawing",
  "cross-stitch",
  "detailed-graphite-portrait",
  "drone-orbit-shot",
  "drone-top-down",
  "editorial-illustration",
  "embroidery",
  "encaustic-wax",
  "etching-print",
  "fisheye-lens",
  "fresco-mural",
  "gouache-illustration",
  "graffiti-mural",
  "graphic-novel-noir",
  "halftone-print",
  "hand-painted-anime-film",
  "impasto-oil",
  "ink-pen-hatching",
  "ink-wash",
  "isometric-illustration",
  "light-painting",
  "line-art",
  "linocut-print",
  "lithograph",
  "long-exposure",
  "low-poly-3d",
  "macro-detail",
  "manga-panel",
  "marker-illustration",
  "modern-digital-anime",
  "mosaic-tile",
  "newspaper-comic-strip",
  "oil-painting",
  "oil-pastel",
  "paper-collage",
  "papercraft-layers",
  "pastel-drawing",
  "pencil-sketch",
  "pixel-art",
  "retro-80s-anime",
  "risograph-print",
  "rubber-hose-cartoon",
  "sand-art",
  "scratchboard",
  "screen-print",
  "silhouette-animation",
  "soft-cel-animation",
  "stained-glass",
  "stencil-spray-art",
  "sticker-art",
  "storyboard-sketch",
  "tempera-panel",
  "tilt-shift-miniature",
  "vector-flat-illustration",
  "voxel-art",
  "watercolor-painting",
  "western-cartoon",
  "wide-angle-environmental",
  "woodblock-print",
];
